### ISSUE TITLE
scaling objects in a scene with a dense trimesh environment causes slowdown

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1065]
try scaling a duck in chess car

**Comment by InfiniteLee** [comment]
This is not scaling specifically, but rather scaling causes objects to penetrate, and penetration with very complex/dense trimeshes seems to cause significant slowdown. The car model in this scene is a case where it is very bad because it contains many high poly sub-meshes that are very small, so even a small intersection with spawned media objects causes many contact points to be generated.

**Comment by InfiniteLee** [comment]
The solution I am attempting is to find a reasonable way to determine if a scene (or possibly sections of a scene?) are high poly, and if so, generate a box collider instead of a trimesh for that part of the geometry.
