### ISSUE TITLE
Confirm the "hit HEAD to get timestamp" approach won't melt reticulum

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#120]
I notice we slam reticulum with HEAD requests on entry to get server ping time, we should make sure this is very cheap to execute on the server (or discuss alternatives.)

**Comment by mquander** [comment]
I still suggest we stop trying to reinvent NTP and use a technique to resolve ownership collisions that doesn't require agreeing on a canonical "timestamp", like the vector-clock-esque one I described initially using sequence numbers and a tiebreaker.

**Comment by gfodor** [comment]
If that approach isn't written down already, mind writing it here? (Sorry, but I didn't see it previously)

**Comment by mquander** [comment]
Sure, briefly: I understand the problem being that two people may race to update virtual state, like taking ownership of a virtual object or (in the future) mutating some other in-room state, like pushing a virtual button. We have two desiderata: 1) ensure that the state is eventually consistent after their actions, and avoid a situation where person A thinks that they did it and person B thinks that they did it and 2) as much as possible, updates should happen with low latency, in the order that they were really performed, and not be reordered.

The current approach is that first, before doing anything, everyone synchronizes their clock. For each piece of state, the last modification timestamp is stored. When you want to update the state, you send a timestamp along with your update. When you receive updated state, you only apply it if the timestamp is more recent than the timestamp you already have. This satisfies 1. For 2, if the synchronization is accurate, it results in updates being ordered by the time that they were performed on the client, which may produce reordering of updates in the presence of differing network latencies.

A different approach would be that for each piece of state, a (sequence number, tiebreak number) is stored. When you want to update the state, you send the next sequence number with your update, along with some arbitrary tiebreak number, like a random integer or your user ID. When you receive updated state, you only apply it if the (sequence number, tiebreak number) pair is larger than the pair you already have. This satisfies 1. For 2, it results in updates being ordered by the time that they were received, which minimizes reordering but may not match the order they were performed in the presence of differing network latencies.

We could use a third approach, which is to store a whole vector clock for each piece of state. That would work great but it sounds more annoying to implement unless there is already a great Javascript vector clock library, and I don't think we need the extra information. My understanding is that the main reason you would use a vector clock over my suggestion is if you wanted to know whether state updates were causally related, which we don't need at all for ownership, and it seemed like we probably didn't need it for most of the kinds of room state that we had at Altspace.

Anyway, I think my second approach is basically better than what we're doing now in every way. I think Kevin had some argument why he thought that the time-of-acting-ordering-of-updates was more desirable than the time-of-receiving-order-of-updates, but I don't remember why he thought it, and even if I thought that would true I still would implement mine for reasons of simplicity.

**Comment by gfodor** [comment]
@InfiniteLee any thoughts on this? basically the primary motivator for me opening this ticket is the burst of HEAD requests we make to the server, which I'd like us to avoid if possible.

**Comment by InfiniteLee** [comment]
The long term solution to avoiding repeated HEAD requests is to add an endpoint to janus/reticulum that returns a timestamp in ms. The only reason we "burst" is because HEAD only returns time in seconds- so we have to average over x requests to get a reasonable approximation in ms. If we had an endpoint in ms to begin with, we'd only need to make 1 request. 

As for which approach is best, I prefer the timestamp one (option 1) For several reasons. For one, assuming you have a good clock sync, it will introduce the least collisions. The odds of two updates happening at the same ms is very small, versus the odds of collisions occurring during the same network frame is an order of magnitude more likely to occur. Furthermore, those collisions are resolved arbitrarily and randomly, as opposed to by time which is at least somewhat fair (again, assuming reasonable clock sync). Right now with the timestamp method we resolve those collisions in favor of the "last" owner (greatest timestamp), but there are cases where a developer might want to favor the "first" owner (e.g. first person to hit the button wins). This would not be possible with the sequence number option. 

Additionally, this extends to being the most correct approach if/when we extend this functionality to be handled by the/a server. (Arguably you can do without clients sending timestamps at all, but again, it makes it more "fair" since you can factor in time over the wire and not simply which message was received first by the server). 

Furthermore, having a timestamp associated with every action is probably desirable anyways- so why not use it for this purpose if its included. 

Now there is an argument to be made about whether or not we should have/expect a reasonable clock sync, and I would argue that it is a desirable feature that we should have available for a multitude of reasons that I won't list here.

**Comment by arpu** [comment]
for now and for saving server requests you could use 
https://time.akamai.com/?iso
(its used for video syncing on dashjs)

**Comment by mquander** [comment]
Yeah, on reflection this is very confusing and I think I have no idea whether the thing that will make people happiest in the future will be wall clock time, wall clock time + sequence number, sequence number, vector clock, or wall clock time + vector clock. It seems like there are cases where having more information about causality than wall clock time provides is helpful, but that you can usually avoid those cases in your application by changing the payload of your network state.

Given this, I would just do the simplest thing possible, which to me is not bothering to try to synchronize to wall clock time, also not bothering to maintain a whole vector clock, and do the sequence number approach. But I have low confidence that I have thought through all the reasons.

**Comment by gfodor** [comment]
thank you for the reference @arpu I think that would be a good change!

**Comment by gfodor** [comment]
Yes I think we should (for now) just update `naf-janus-adapter` to fetch the time from Akamai:
```
const res = await fetch("https://time.akamai.com/");
const time = new Date(parseInt(await res.text(), 10) * 1000)
```

**Comment by gfodor** [comment]
cc @robertlong

**Comment by gfodor** [comment]
I figured out a way to rig this up with cloudfront, so we get the clock time from the edge node.

**Comment by gfodor** [comment]
https://timecheck-prod.reticulum.io/index.html

**Comment by robertlong** [comment]
I think we are handling this correctly now https://github.com/mozilla/naf-janus-adapter/blob/master/src/index.js#L607

Closing.

**Comment by gfodor** [comment]
it's still pretty bad, but hasn't burned us yet so /shrug
