### ISSUE TITLE
[UX] No affordance to cancel out of media browser in desktop VR

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1277]
Scenario - I tried to create an item in my Rift, was prompted to look at my desktop to continue. I didn't want to take my headset off, but I had to in order to cancel the search operation. I suggest that the menu item saying 'take off your headset to continue' should have a dismiss option that cancels the media browser flow.

(Oculus Rift w/ Touch, Nightly, Windows 10)

**Comment by gfodor** [comment]
I took a quick look at doing this earlier -- main issue is that the tip shows for a couple of different reasons (login page, media browser, etc) and the code involved does not have context to know how to "back out" of those in a direct way. However, in practice, I think doing a history "back" may work properly for the cases we have now, so we can try that, but I was nervous doing it since it's not future-proofed.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1316
