### ISSUE TITLE
[UX] Room creator can't change scenes unless signed in

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1279]
While giving a demo of hubs, I was showing a new user how she can easily change the environment, because this was something she was very excited about. I https://github.com/mozilla/hubs/pull/1261 had been merged, I would have seen that she didn't have permission to change the scene. This is surprising. I suggest we loosen this restriction. If not, then I suggest we message this more clearly than in https://github.com/mozilla/hubs/pull/1261 : "You do not have permission to change the scene" does not tell you how to get that permission.

**Comment by gfodor** [comment]
I think the plan here is going to be to stick a token in the user's local storage if they create a room and are not signed in, which will give them the right to become the owner if/when they sign in. Then, privileged actions in unowned rooms (like changing the scene) will drive them through the sign up flow similar to pinning.

I don't think we should loosen the default scene changing permissions: if we did so, it'd likely rule out Hubs as a viable app for semi trusted audiences since a random user could just change the scene during an event, which is very destructive. The long term solution is to allow room owners to define permissions, so sometimes they can grant permission to scene changing to all.

**Comment by gfodor** [comment]
https://github.com/mozilla/hubs/pull/1305
