### ISSUE TITLE
Feature: Make name tag visibility a setting

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1300]
There should be a way to hide name tags - for certain scenarios, you will not want or need to identify users in the room 100% of the time. There are some open questions about this: 
* Should this be an "always off, always on" toggle?
* What is the default state? (I think on)
* Are there scenarios where the nametags should always be visible, regardless of the setting, e.g. if the user is in pause mode? 
* Where should this setting live in the UI? Somewhere in the user list?

**Comment by brianpeiris** [comment]
- How do we ensure the setting can be discovered?
- Should the setting be per-user, per-room, or both?
- Should we also hide badges and profile pics if/when we add them?

**Comment by gfodor** [comment]
Unfortunately I can't think of a good general purpose place in the UI for this toggle.

My 2c is a design that probably balances the various tradeoffs reasonably beyond not knowing where to put the toggle:

- By default, tags show on cursor hover and all show on pause
- For scenarios where you want to show nametags always, you opt-in and it sticks just for that session (or maybe that room)

My justification for off by default is that I expect most users to just use the default, and the default in this case aligns better with our focus on in-network room sharing.

I think ideally hiding the nametag should be all or nothing, since my 2c is that having a small nametag/badge is only marginally better than a big one, vs none altogether which is a big win for social presence.

If we don't feel bad about burying it, we could put it under a "Room Preferences..." modal that lets the user adjust room-level, personal settings. This probably would be OK unless we have scenarios where we think having rapid access to it (esp from within VR) is necessary.

**Comment by misslivirose** [comment]
Likely will be done before H1 but putting there in the interest of not assigning new Q4 work a week before it ends

**Comment by johnshaughnessy** [comment]
I did not know about this discussion before implementing the option, "Only show nametags in pause mode" in the user preferences screen. 
 That at least partially addresses these concerns. I'm open to suggestions for how this can be improved further.

**Comment by misslivirose** [comment]
I think that the implementation as it exists today is probably sufficient for the primary use case where screenshots and video can now be captured without having all of the user names available. We could still consider what the proper default is.

**Comment by gfodor** [comment]
Closing this for now unless it comes up again for a new use-case.
