### ISSUE TITLE
Movement controls occasionally get 'stuck'

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1309]
This happens to me about once per week and we observed it today in one of the CHI viewing rooms - a movement control (I've been seeing this on desktop) gets stuck in a particular direction and you're stuck moving that way indefinitely. Sometimes, you can get out of this by repeatedly using the WASD keys to "unstick" but other times it requires a refresh.

**Comment by j-conrad** [comment]
Cross-linking to related issue(s):
https://github.com/mozilla/hubs/issues/259#issuecomment-486442301

**Comment by johnshaughnessy** [comment]
We fixed parts of this issue:
 - you had to press SHIFT + the stuck wasd keyup (now you don't have to press SHIFT).
 - we clear the key presses on blur (so you stop moving if we receive a blur event).
  
This can still happen if you hold shift and then right click in firefox as outlined in https://github.com/mozilla/hubs/issues/1263. We do not get `contextmenu` or `click` events when this overriding behavior happens, but we do get `mousedown`, so we could stop your movement on mousedown + shift + firefox. 

Then the only other way I know this behavior can happen is if we do not get a `blur` event when the user focuses a different application / window. Since the browser fires key events repeatedly  while the user holds a key down, we could implement an "automatic release" of any keys that haven't had a recent "down" event. That would catch cases like this where we never got an explicit "up" event to end the movement.

**Comment by misslivirose** [comment]
I like the idea of an automatic release - @emclaren hit this today and Blair mentioned still seeing it frequently

**Comment by emclaren** [comment]
I hit this bug often - I have also recently had an additional bug happen immediately following the controls getting stuck where everytime i click in the chatbox, a long video gets recorded. thus leading to lots of videos popping out about a few minutes later all at once. This has happened to me twice in the last week, but I cant quite figure out what leads to this (other than the controls getting stuck first).

**Comment by gfodor** [comment]
If it’s the “x” key, we can consider dropping that feature altogether
unless someone objects: I added it completely speculatively and it seems
like it has regressed into being buggy

**Comment by misslivirose** [comment]
I hit this a lot less often these days, but ran into this yesterday.

**Comment by misslivirose** [comment]
There were three reports of this happening during XR Access

**Comment by emclaren** [comment]
It was noted that one of the users this happened to at XR Access Symposium was using a screen reader and was unaware that this was happening because we have no feedback when users move. 

related to this: https://github.com/mozilla/hubs/issues/2701

**Comment by emclaren** [comment]
This happened to me today because i accidentally pressed Command+S at the same time. Also noted that Command+A makes the controls get stuck as well.

**Comment by matthewbcool** [comment]
unable to repro, closing for now.
