### ISSUE TITLE
Feature: Improvements to placing media with controls and dedicated media zones in Spoke

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1324]
It would be incredibly helpful to have a way for a Spoke template to contain a dynamic surface to stick video content to once in Hubs. There are some open questions around this, but I think that this is a must-have to elegantly support the "shared viewing" user stories. It is difficult to position and change video urls in Hubs with the present interactions. 

User flow: 
- I create a Spoke template that has a 'media surface' element
- I use the Spoke template to create a Hubs room
- I find a video or Twitch stream in the media browser and spawn it in world
- I drag it into range of the media texture (perhaps there is a confirmation step here?) 
- The video auto-fits itself into the orientation and position of the media texture element

Open questions:
* Would we want to have the surface support only videos, or any 2D plan content (video, images, camera, desktop/window sharing)? 
* What does the UI look like in Hubs to select an item for the media surface? A minimum interaction could just be to drag the item to intersect the media surface or be placed within a certain distance.

**Comment by gfodor** [comment]
Additional requirement: these should work for shared screens and cameras as well, which may run up somewhat against the idea of 'unlocked' media given those are technically not URL based media.

**Comment by emclaren** [comment]
Received feedback from a community member that they are interested in this type of feature:
"It would be nice if I could define an area that can be used for projections. So that when i share my screen i could select a projection area."

**Comment by misslivirose** [comment]
There are some open design questions about whether or not the objects should be placeholders or if media should just intelligently know how to land on surfaces. Could be both.

**Comment by gfodor** [comment]
Notes from the meeting:

- After some back and forth, the conclusion was that we should introduce two first-class elements to Spoke, a 2D and 3D media zone.
- These zones will have the union of all of the relevant properties of the relevant media, and will not allow placement of incompatible media
- Properties will be collapsed by default for each type (audio, video, etc) to reduce clutter. Creators can open the properties for a given type to customize.
- The "locked"/"unlocked" concept was discarded, since it results in a semantic problem: having an unlocked video for example may or may not allow pdfs to be placed, which is problematic.
- It would be handy to have a "Convert to Zone" action in spoke, so a scene with media can be remixed into a re-usable one with zones.

We did not cover the topic of in-hubs UX.

**Comment by misslivirose** [comment]
The design / feature work should also tackle the overall issue of placement in Hubs rooms. See: #1978

**Comment by mohoman** [comment]
I can't speak as much to how to implement it, but I can comment on how the User Experience should be:

1- When rooms are designed in Spoke, there would be an item that would be a sort of "Sticky Board" that could be added to walls within the room
2- These "Sticky Boards" can receive any type of 2D media (Documents, videos, web pages...) and automatically resize them to the full dimensions of the Sticky board
3- Users in the room can still spawn 2D items the same way they do now by copy-pasting links or dragging links and documents into the room
4- When, let's say a pdf document, is spawned in the room it can be dragged to the desired sticky board and dropped on it
5- When the sticky board sees an item has been dropped near it, it takes it and displays it
6- The PIN function can still be used the same way, if someone wants to setup a room with preloaded presentations for people to see whenever they enter the room, they can just Pin them. Maybe there could be an option so that only the owner of the room can pin/unpin presentations. That would be best

To see an example of how Wallboards are used in a VR environment, please look at how Virbela does it https://www.virbela.com/.

**Comment by mohoman** [comment]
Not sure how complicated this would be todo, but a fun feature to have would be the ability to co-browse within the room. So if a webpage is displayed in the room, you could actually click the link on the page

**Comment by andybak** [comment]
I'm researching art galleries in Hubs and I've built VR art galleries in Unity in the past.

I'm worried that the solution here won't work for me as it will be too specific to "putting flat media objects on walls". I know that sounds like an art gallery but consider that pictures in a gallery usually have depth. They sit on canvas or in a frame. So I'd want to define the object that each media object sat on. 

Rather than making this overly complex to solve my problem in addition to the original one - what ingredients would solve the general problem?

I suspect that it's a mixture of:

1. Snapping to surfaces
2. Defining constraints so that some objects can be locked to surface with a certain orientation
3. Defining placeholder objects with slots for video or images to be added
4. Logic for placeholders to resize to fit their content (or at least match the aspect ratio)
5. Align and distribute controls for groups of objects as found in most 3D editors and 2D drawing apps.

Implementing stuff like this might end up solving problems we haven't even considered yet.

**Comment by netpro2k** [comment]
We also need to think about how this works for screen/camera sharing as discussed in https://github.com/mozilla/Spoke/issues/929
Leaving it as its own issue since it may have its own set of solutions, but wanted to link here since it could be related.

**Comment by brianpeiris** [comment]
I think we can call this closed?

**Comment by misslivirose** [comment]
Yep!
