### ISSUE TITLE
[UX Enhancement] Object's Menu

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1460]
As a user, the object's menu should always look at me so that I can rotate, scale, delete... the object.

![ObjectMenu](https://user-images.githubusercontent.com/38146102/60176291-e3feae80-97e3-11e9-944b-b72e3c67145e.jpg)

**Comment by gfodor** [comment]
Yup this is something we've wanted to fix for a while. The current algorithm is designed to be a good one-size-fits all solution since we also want to make sure it works well on 2d flat planes. I think the current consensus is that for 3d objects of a minimum extent we should project the menu on a 'billboarded' cylinder .

**Comment by misslivirose** [comment]
See #1489 for additional discussion about how this could work, as the current design makes it difficult to access all menu elements depending on where in the environment an object is placed.

**Comment by misslivirose** [comment]
Closing this to track in #1187
