### ISSUE TITLE
Add room object list to a Hubs room

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1462]
As an advanced user, I would like to see a list of all my objects in my scene so that I can delete/bring them to me if they fall under the boundaries.

**Comment by kwadroke** [comment]
Maybe allow resetting of the objects' positions to a former state? Possibly a "Soft Pin"?

**Comment by misslivirose** [comment]
What do folks think about linking this with #1461 in the same UI panel?

Other open questions: 
- What is the permission level that can access and use the object list? Given the object permissions (#1517) feature, I would think that we'd only want the object list to appear for people who can create objects in the room, but there's been some discussion about whether this should be an owner-only feature or not. 

- What kind of actions can be taken from inside the list? My take is delete / 'bring to me' / maybe 'pin'. 

- Where does the UI for this live? We've been thinking that it might combine with the presence list (so that becomes a record of who/what is in the room) but open to some other ideas.

**Comment by misslivirose** [comment]
Another open question: What do we show in the list to make it useful? The raw url for the media probably wouldn't provide enough context, so we might want to combine the object list with @johnshaughnessy 's new inspect mode when you click on an object in the list to get a preview of what it is that object is linked to (as opposed to trying to do thumbnails).

**Comment by flowpoly** [comment]
Hey all, I did some mocks for this feature: https://www.figma.com/file/MV6fCW3schGwXrfbtmVbyQxf/Hubs?node-id=27%3A184

**Comment by johnshaughnessy** [comment]
@flowpoly 's mockup informed the work I'm doing in #1749 . Thanks a lot -- those visuals made it a lot easier to start the work!

There are some differences in my first-pass implementation due to a few factors: 
 - In order to keep a more consistent feel with the way the participants list entries work, I moved the operations you can do on each object into a modal dialog that pops up when clicking the row, rather than having each of the operations represented with small icons in the list.
 - I do not have nice names for the media objects in the room, so I truncate their URL in the list and then display them in full in the modal that pops up. 

The icons I used were taken from font-awesome for convenience but I'd be happy to swap them out for different ones. I see one icon in the mockup for 3D models and one for videos -- if we like those better I'll swap them in. We also want icons for images, pdfs, and unknown media types.

Regarding @misslivirose 's concern above about who has permission to view the list -- What I tried doing first is to let anyone view the list, but the buttons that show up depend on what you have permission to do in the room. For example if you do not have pin/unpin permissions then there is no pin/unpin/delete button in the menu. I think "teleport to this object" (when implemented) is an example of a feature that we want available to everyone, just like "inspect this object" (by hovering on it in 2D or touching/clicking on it in mobile or mobilevr).

**Comment by johnshaughnessy** [comment]
Also -- I agree that objects list and participants list should be combined. I think the only thing I'd want us to do before doing that is allow you to inspect other participants (provided they're in the room) so that the UX is consistent. There were some annoying (but not major) technical hurdles required to accomplish this so it is not done yet.

**Comment by misslivirose** [comment]
This sounds like it's heading in a great direction!

**Comment by flowpoly** [comment]
@johnshaughnessy @misslivirose This is looking great! Awesome job! A couple of things to consider:

We could show the dropdown when the button is clicked and say 'No objects in the scene, click here to add one!' which sends the user directly to the Wand interface. We could also just make the button look less interactive since it serves no purpose unless there are objects in the scene. We could make it a little grey or maybe hide it all together.

I think we talked about this before, but there's no way to parse the object's link to say something like 'Rubber Duck'? Literally the title of the 3D model or video?

**Comment by misslivirose** [comment]
We landed on having the hover state difference to account for the fact that we can't guarantee getting names from model urls. For the first pass, we landed on using the URL + inspect because we're not accessing names and some media content (for example, anything that is uploaded from a computer) would just have no title available at all. 

I like the idea of handling the empty list case better, though I'd like to move that to a new issue (#1775) and resolve this one to better track suggestions for improvement independently of one another.
