### ISSUE TITLE
[UX Enhancement] Automatically Find Device

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1469]
As user, I wish Hubs found my VR headset on its own, but I should always be able to change it if it finds one which I don't want to use.
VR should take priority over PC.

(This may happen already since I don't currently have a VR headset, but it seems that this isn't the behavior)

**Comment by gfodor** [comment]
What specifically are you suggesting? Our entry flow is designed to ensure user control and takes advantage of all of the various things we can know via the WebVR APIs, and also tries to have a good experience for people who have both connected and standalone VR headsets.

**Comment by flowpoly** [comment]
@gfodor This one is tricky because on one hand, it would be nice to should run Hubs if it detects my VR Headset, but at the same time that takes power away from the user. 
It would be nice to have data on how many users with a VR headset plugged in just use the actual headset instead of wanting to use PC.

Long story short, if I am getting on Hubs and I have my headset enabled, it should auto-select my headset, but if it doesn't find one then it should auto-select PC. Let me know if this makes more sense!

**Comment by gfodor** [comment]
Ah. The current design is intentional: it does not place connected VR headsets as a "higher priority" affordance if one is detected. In practice, even if you have a VR headset attached to your computer, it's often the case (if not the majority of the case) that you want to enter rooms in 2D mode. We don't have data on this split specifically, but we do know that the vast, vast majority of sessions in Hubs are 2D in general.

So we give the user the choice, and actually have the 2D case be the primary path even if we detect a headset. Anecdotally, it's super common to go into rooms in 2D vs VR for me personally, since VR takes more effort to set up and use.

**Comment by flowpoly** [comment]
Closing for now since we need more data + everyone seems to utilize Hubs in '2D' instead of VR headset most of the time.
