### ISSUE TITLE
Sharing camera unmutes microphone, doesn't update UI <n/t>

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1518]

**Comment by misslivirose** [comment]
Repro Steps (Client A and B are connected to the same room) 
1. On client A, mute microphone
2. Confirm that client B cannot hear client A
3. On client A, share the webcam on the client
4. Confirm that client B can now hear client A
5. Confirm that client A's HUD still appears muted

Given microphone sensitivity, this feels like a slightly higher priority bug. It seems unlikely that there will often be use cases where you want to share camera but NOT voice, however, it seems important to, at a minimum, update the HUD state so that the microphone becomes unmuted when camera sharing begins.

**Comment by netpro2k** [comment]
Hmm seems wrong that the sharing camera unmutes you.

**Comment by gfodor** [comment]
This was fixed at some point
