### ISSUE TITLE
Flip Camera Button

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#1574]
**Is your feature request related to a problem? Please describe.**
In 2D mode, when you spawn a camera it always faces you and rotating it to face the other way requires a lot of effort.

**Describe the solution you'd like**
It'd be nice to be able to click a button to flip the camera orientation.

**Comment by gfodor** [comment]
seems like a good idea, tho it's a bit weird because the camera is functionally equivalent regardless of which way it's facing, except the viewfinder is offset differently

**Comment by johnshaughnessy** [comment]
what if we flipped objects PI radian around Y whenever you begin to rotate them? That means to do the same behavior now you'd have to double-click the button, but it makes the flip-180 case very easy.
i.e. https://github.com/mozilla/hubs/pull/1575

**Comment by robertlong** [comment]
Also check out #1576 for a combined design concept.
![CameraUI](https://user-images.githubusercontent.com/1753624/61978917-4dbad580-afa7-11e9-8a43-38019cbe3a58.png)

**Comment by johnshaughnessy** [comment]
Like Robert, I also want a button that rotates the camera (and other 2D media) 180° in the xz plane. Should it be a different button than the regular rotation button? Both capabilities seem important for non-6DOF users.

**Comment by gfodor** [comment]
I'd probably need a deeper design comp to grok this. It's unclear to me how
those buttons fit together. A couple of things:

- I didn't introduce a control for the timer to reduce the DoF/number of
buttons

- The current design has the numbers really big so you can read them in VR

- the timer is there in part because without it you'll always be taking
pictures or starting videos of yourself using the cursor to click the button

I agree breaking out photo and video mode as a separate DoF could have
merit, but it could also be confusing to have an additional modality on the
main controls

**Comment by gfodor** [comment]
We could potentially address the need to flip the camera by dropping the
metaphor somehow. Like I mentioned there is no functionality difference
between the front and back other than the viewfinder placement. Maybe
there's a different camera metaphor we could use to make them completely
identical.

**Comment by gfodor** [comment]
Oh actually you're right Robert, silly me

**Comment by misslivirose** [comment]
Closing this since 1575 was merged and now provides the 180 flip for all objects! Great suggestion
