### ISSUE TITLE
Feature: Establish room capacity and scaling guidelines

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1617]
We have started to see some degradation of performance, specifically around successful audio transmission, when users are in rooms with 30+ avatars. This task documents a need to explore scaling and room limit restrictions.
 
- [ ] Test capacity limits with existing infrastructure
- [ ] Design requirements
- [ ] Code & Review
- [ ] Release
- [ ] Release Media (blog post / documentation updates)

**Comment by gfodor** [comment]
As part of this, it seems essential (for the events case) that there be a mechanic for the organizer to let a person into the room temporarily and override the capacity to ask a question.

One variant of this is that someone can ask from the lobby to enter the room, and the moderators can grant access for some duration (90s etc) After the duration completes, the user is returned to the lobby. This would be quite difficult to implement currently since up until now the entry flow has been unidirectional from lobby to room -- the current implementation would require a lot of work to be able to move back and forth between room and lobby.

**Comment by misslivirose** [comment]
See also: [https://discourse.mozilla.org/t/graceful-scaling-for-rooms-at-capacity/38539](https://discourse.mozilla.org/t/graceful-scaling-for-rooms-at-capacity/38539)

**Comment by gfodor** [comment]
one mental model i've been kind of riffing on:

- 12 concurrent avatars for mobile VR (design goal)
- 24 concurrent avatars for desktop (design goal + enforced cap)
- 250 concurrent viewers for larger events (design goal)

**Comment by misslivirose** [comment]
Since we have the initial room cap in, I'm bumping the rest of these questions out to consider as part of H1 2020 planning

**Comment by misslivirose** [comment]
Closing this as it generally encapsulates work that we've done with dialog. We can create a new issue for future scaling work.
