### ISSUE TITLE
[UX Enhancement] Exit Confirm Modal

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1671]
**Description**
As a user, I would expect a modal to pop-up in case I accidentally close the Hubs room I am in.

**To Reproduce**
1. Create a Hubs Room.
2. Exit the window.

**Expected behavior**
As a user, I would expect a modal to pop-up in case I accidentally close the Hubs room I am in.

**Additional context**
Find a screenshots attached that represents a way to tackle the problem.
![leavestay](https://user-images.githubusercontent.com/38146102/63298964-bb0a0f80-c2a2-11e9-845e-13921c98ba0b.PNG)

**Comment by misslivirose** [comment]
We don't have a way to directly confirm whether an exit click is intentional or not, and I could see prompting this being an annoyance in the majority case where people intend to leave the room. Are there other examples of chat or multi-user places that use this method independently of the user actually entering data that hasn't been submitted?

**Comment by misslivirose** [comment]
I've done a bit more research to see if there are best practices around this for non-form entry scenarios, and I'd personally prefer to err on the side of assuming intent by a user. Putting up this message any time I closed a Hubs room tab would get tedious, and trying to identify logic that would try and assume intent to leave vs. accidental closing feels like we might be doing our best guess. I'm going to close this as a won't-fix. 

We can re-open it and re-evaluate if we feel like we either a) have a good set of specific criteria that designates an accidental closure or b) evidence of other similar design patterns for sites that don't involve unsaved data
