### ISSUE TITLE
Mic Indicator state reported muted but wasn't

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#1695]
**Description**
Mic indicator showed muted, but users were still audible

**To Reproduce**
Unknown, but had multiple reports of it happening in a single, small session

**Expected behavior**
Mic muted indicator always reflects current state of user mic input

**Comment by gfodor** [comment]
https://github.com/mozilla/naf-janus-adapter/pull/79

**Comment by johnshaughnessy** [comment]
At least one way this bug can manifest is fixed here: https://github.com/mozilla/naf-janus-adapter/pull/83
Will get a review and deploy

**Comment by johnshaughnessy** [comment]
Unclear if this issue is fully fixed or not, so keeping it open.
Also, we should do what @netpro2k suggested and make sure that the visible mic state is tied _as directly as possible_ to the actual state that determines whether data could possibly be sent, rather than relying on some derived state. I'm not exactly sure what the "actual" state we should be looking at is.
