### ISSUE TITLE
Make links object clickable similar to objects with URLs in Hubs

### ISSUE THREAD

**Issue by ducile** [mozilla/hubs#1782]
When creating a link object with a link to a website it would only show a screenshot of that website in Hubs. It would be nice to have that link also clickable.

Side note: The link object shows "Link to a Hubs room" as its description. So I thought it would only accept Hubs room links.

Workaround:
When using a video object it works for some reason.

**Comment by robertlong** [comment]
Thanks for filing this! I've moved this to the Hubs, repository since it is a bug in Hubs.

The link component inflator needs to be fixed. It's using `media-loader` which has the wrong behavior. https://github.com/mozilla/hubs/blob/master/src/gltf-component-mappings.js#L204

The description is purposely `Link to a Hubs room` because that's the only type of link that currently works correctly. When Hubs has support for any link, I'll change the description.
