### ISSUE TITLE
"Enter on Device" Wording in Lobby is Unclear

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1803]
**Description**
Multiple users with connected VR devices have reported confusion over the text prompt when joining a Hubs room.

The Lobby screen says "**Enter on a Device** Standalone VR or phone" (see screenshot 1). 

It might be more clear if the heading said something like "**Standalone VR**  wireless headsets and phones".

This would also be more consistent with the prompt on the following screen (screenshot 2).

**To Reproduce**
1. Go to Hubs room with a connected VR headset

**Expected behavior**
NA

**Screenshots**
Screen 1
![snip of hubs loading page](https://user-images.githubusercontent.com/6835324/66509973-f34ef280-ea88-11e9-936a-5da267aa13c4.PNG)

Screen 2
![snip of hubs loading page 2](https://user-images.githubusercontent.com/6835324/66509981-f77b1000-ea88-11e9-9380-a12ecc35b027.PNG)

**Hardware** 
NA

**Additional context**
Would be happy to hear other wording suggestions

**Comment by gfodor** [comment]
My suggestion would be to change this copy to say
primary: "Enter in Standalone VR"
subtitle: "Oculus Quest, HTC Focus" (I know we try to avoid naming devices, but currently in the existing market this seems OK)
or alternatively subtitle of "Wireless VR Headsets" if we don't want to have those devices named explicitly

I think the use of the term phone is just adding confusion so suggest we drop it.

Also, previously we put the standalone link UX on the second screen, but this was not discoverable. The earliest versions of hubs had device/entry mode selection as the primary CTA on the landing page, but this broke down over time as the number of options increased and the competition for real estate increased due to our lobby experience. In general, the current UX disfavors wired headset users since they are currently not able to ascertain from the landing page that they will be given the option to choose their connected device on the second screen. However, it seems worse to push that selection into the lobby view since we are already out of real estate. It does seem critical, however, that standalone users have the CTA on the landing page.

**Comment by ArthurCose** [comment]
The "Enter on a Device" button also displays "Standalone VR or PC" as the subtitle on mobile. It seems to be more of a "Enter on a Different Device" button.

This button was a source of confusion for me as well: "Yes I would like to Enter on a Device, and it's the one I'm using."

If text wrapping doesn't fit the design restrictions of this button I'm not sure what to name it, but I still suggest something that makes it clear that it's for entering on a different device than the one the user is currently using.
