### ISSUE TITLE
quality=low query string no longer works

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#2054]
**Description**
Adding `?quality=low` should put Hubs into low quality mode. It no longer does this. This probably happened around the same time as we added user preferences.

**To Reproduce**
1. Visit a Hubs room in a private tab with `?quality=low` set.
2. Observe that the standard material is still being used.

**Comment by johnshaughnessy** [comment]
I removed this query string parameter (but forgot to remove the tip from README.md / the docs) when adding the preference screen: https://github.com/mozilla/hubs/pull/1987/files#diff-36e9875da4ba69fe26a79e004718180cR179

My concern with having both the user preference AND the query string parameter is this: If the query string parameter is present, it makes sense to me that it takes precedent over the user preference, since presumably you type that in only when you want it. However, I do not think the a query string parameter should change the stored user preference in local storage, because if Bob sends Alice a room link with `?quality=low` but Alice's previous preference was set to high quality, I think it would be confusing if Alice's preference was stuck at "low" for future sessions. So, if both a user preference and a query string parameter are present, I think what should happen is that the query string parameter takes precedence for the duration of the session, the user preference remains what it was in local storage ("high quality" for Alice, in this example), and I think the user preference screen should indicate to Alice that her preference is being overridden during this session by the query string parameter. 

I did not implement this "overridden preference" UI, and preferred to remove the query string parameter for now. If having the query string parameter is important for development or other reasons, then I suggest we take this path.

**Comment by robertlong** [comment]
That makes sense to me. I'm fine with having it only exist in the user preferences page 👍

**Comment by johnshaughnessy** [comment]
Closing as per discussion above

**Comment by mauriciomartinez-itesm** [comment]
There's the possibility that a user has a low end computer and can't load the full high quality scene, having it as a query string can make it easier for users to load the scene without the need to load the biggest one first (which defeats the purpose of having a low quality setting to start with)
