### ISSUE TITLE
Provide user pref to disable/override the auto-pixel-ratio system

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2141]
**Is your feature request related to a problem? Please describe.**
Elgin uses a mac computer and often wants to take a high-resolution screenshot. The auto-pixel-ratio system automatically blurs her screen in an attempt to improve performance, but in this case she would prefer to have a low framerate with a crisp image.

**Describe the solution you'd like**
User pref to disable (temporarily or permanently) the auto-pixel-ratio system.

**Describe alternatives you've considered**
Lower the threshold for when this system kicks in, or try to improve performance in other ways. (What if we only render 1 object per frame? ;) )

**Comment by brianpeiris** [comment]
@emclaren Would you prefer a setting in the preferences dialog, or would a query string parameter suffice?

**Comment by emclaren** [comment]
thanks @johnshaughnessy for writing this up!

a query string would be just fine if its easier for you, however, long run I would prefer to have it in preferences so I could just toggle it to be always off and not have to worry about remembering to flag it every time I attend an event in Hubs. 

I also suspect this would be useful for other non-expert hubs users, because it may be confusing for them when the resolution drops suddenly mid-way through using hubs.
