### ISSUE TITLE
Fix getting stuck in a waypoint on mobile

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2221]
If you are on a touchscreen (and cannot teleport), and a scene author spawns you into a seat that disables motion, you can't teleport out of it. 

There ought to be some way to get out of a seat when using a touchscreen.

**Comment by misslivirose** [comment]
Bumping this issue up because it's a pretty unfortunate situation to get into. Related to issues with input generally for mobile.

**Comment by dankessler** [comment]
I ran into this issue while demoing hubs with a family member who was using an iPad. Because she has touchscreen controls she has no teleport, and when she "sits" in a chair she gets stuck and movement is disabled. I was able to replicate this on my own iPad. On an iPhone, motion remains enabled and I'm able to "walk" out of the chair, but not on my iPad. I think this is because the fix in #2336 corrects things only if on mobile by checking [`AFRAME.utils.device.isMobile()`](https://github.com/mozilla/hubs/pull/2336/files#diff-d0c85cac4886c13e25d3217e8aacddb6fb932f62dba323beed27d7ffd0f7cab3R18), so I assume this method will return TRUE for e.g., an iPhone, but FALSE for e.g., an iPad. Instead, I think we probably want a predicate to determine if the device is using touchscreen controls. The `detectTouchScreen` function [here](https://github.com/mozilla/hubs/blob/00cc63e58079bebd63f3115b49038da60180d59b/src/utils/detect-touchscreen.js) looks promising.
