### ISSUE TITLE
Hubs room creation/joining broken in Edge

### ISSUE THREAD

**Issue by jarileon** [mozilla/hubs#2425]
**Description**
When trying to create or join a room on Edge only a blank screen is seen and a JS syntax error is printed in console console: 

![image](https://user-images.githubusercontent.com/28865955/80363394-d6470900-888c-11ea-8c46-3e2b1ed8cc9c.png)

**To Reproduce**
1. Go to hubs.mozilla.com on Edge 
2. Click on 'Create Room'
3. See error in browser console

**Expected behavior**
Room creation / joining works

**Hardware** 
 - Device: Lenovo Legion Y740
 - OS: Windows 10
 - Browser: Edge

**Additional context**
It is said "Hubs works best in Firefox and Chrome, but it also runs on Edge, and desktop Safari." in https://hubs.mozilla.com/docs/hubs-troubleshooting.html.

**Comment by misslivirose** [comment]
I'm curious that this wasn't seen earlier (perhaps because Edge 79 was relatively recent, and when they added data channels?) but from my cursory investigations it looks like optional catch binding syntax was not ever merged into Edge production (https://github.com/microsoft/ChakraCore/pull/5310) given the switch to Chromium. I just tested on Chromium-based Edge (https://www.microsoft.com/en-us/edge) and it looks like this isn't an issue there. 

At the minimum, I'll update our documentation to specify this.

**Comment by misslivirose** [comment]
Resolving this as this is fixed with Edge 79+ and we've updated our supported browser matrix to specific which minimum version of Edge is supported:
https://hubs.mozilla.com/docs/hubs-create-join-rooms.html#supported-browsers
