### ISSUE TITLE
Gamepad doesn't register right joystick X axis input for desktop gaze orientation

### ISSUE THREAD

**Issue by jabfrei** [mozilla/hubs#2449]
**Description**
When using an XBox gamepad with Hubs, the position joystick (left) input works, and the orientation joystick (right) registers Y axis input but not X axis input. I've tested this on multiple computers with Firefox, Edge (Chromium), Chome, and the Windows Hubs app, with the same issue recurring. 

**To Reproduce**
1. Using a gamepad, attempt to orient yourself with the joystick along the X axis. 

**Expected behavior**
The joystick should allow for X-axis input

**Screenshots**

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Firefox, Edge (Chromium), Hubs App (Windows)

**Comment by luser** [comment]
FWIW it looks like this is what's supposed to map that input to camera movement: https://github.com/mozilla/hubs/blob/4be04dd1e5db86822d8fd2fbcfae2e111a190c4e/src/systems/userinput/bindings/xbox-controller-user.js#L93-L102

**Comment by luser** [comment]
I poked at this a bit locally. Using Chrome (since Firefox doesn't map my gamepad to the standard mapping), If I press right on the right stick and press the `l` key on the keyboard to log a debug frame, I can see that the value is being seen properly. In the console under `frame -> values` I see:
```
/actions/angularVelocity: 0.6
/device/xbox/axis/rightJoystickHorizontal: 1
/vars/xbox/deadzonedRightJoystickHorizontal: 1
```

The specifics of how input gets mapped to camera and player movement are a bit unclear to me. I *think* it's the `pitch-yaw-rotator` component that controls this, in which case it'd be this code:
https://github.com/mozilla/hubs/blob/4be04dd1e5db86822d8fd2fbcfae2e111a190c4e/src/components/pitch-yaw-rotator.js#L53-L67

That seems to honor both `paths.actions.cameraDelta` and a `rotateX` event. From the debug frame logging earlier I see `/actions/cameraDelta: (2) [0, 0]`, so that's clearly not being set. The `rotateX` event seems to only be used by the virtual onscreen gamepad controls:
https://github.com/mozilla/hubs/blob/0c1ea53a923dca32b59782268685d746b0acad0c/src/components/virtual-gamepad-controls.js#L195

Per the link in my previous comment it seems like `cameraDelta` always has a zero `x` component from this bit:
https://github.com/mozilla/hubs/blob/4be04dd1e5db86822d8fd2fbcfae2e111a190c4e/src/systems/userinput/bindings/xbox-controller-user.js#L118-L125

I would guess the piece that's setting `angularVelocity` actually needs to be setting `cameraDelta.x`? I'll try that and see if it works for me locally.

**Comment by luser** [comment]
This works, I have a PR up:

**Comment by InfiniteLee** [comment]
It looks like this may have accidentally gotten removed from `character-controller` during a refactor here: https://github.com/mozilla/hubs/commit/5c5b720462f3e3bbdadfcaff4a07cd3602110379#diff-3f365e8e594b0992bc5206c0a3f44277L223
