### ISSUE TITLE
Avatar GLB URL feature is broken

### ISSUE THREAD

**Issue by jarileon** [mozilla/hubs#2532]
**Description**
Setting the avatar via Avatar GLB URL feature is broken - even when setting avatar that clearly is OK (selectable otherwise via the avatar browser GUI). 

**To Reproduce**
1. Create a room
2. Go to avatar browser via "Set Name & Avatar"
3. Right click some avatar and copy its URL to clipboard
3. Use the Avatar GLB URL and paste the URL to avatar and press Apply
4. See error "Loading failed - Please use another avatar"
5. Observe the syntax error in console

**Expected behavior**
Settinng avatar via GLB URL works.

**Screenshots**
![image](https://user-images.githubusercontent.com/28865955/83264691-23d6ce80-a1c9-11ea-940f-c2e435aedc2d.png)

![image](https://user-images.githubusercontent.com/28865955/83264700-29341900-a1c9-11ea-9bcb-6416440ede38.png)

**Hardware** 
 - Device: Lenovo Legion Y740
 - OS: Windows 10
 - Browser Chrome, Firefox

**Additional context**
Please fix fast, this is more important feature than you might think! =)

**Comment by misslivirose** [comment]
Hey @jarileon - This is happening because you are pasting a URL to an avatar listing instead of to a .glb file. 

When you right-click, you get the URL (for example, https://hubs.mozilla.com/avatars/Nt7QPw3) to a listing. The 'Avatar GLB' dialog is only if you want to use a .GLB file directly as your avatar. 

What is the use case for this instead of just using the button?

**Comment by jarileon** [comment]
Ok, I have misunderstood how the feature was supposed to work. The use case would have been providing a way to select special avatars for some users that are not selectable by other users. But turns out this is possible by delisting avatars and providing them the listing URL. I will close this ticket.
