### ISSUE TITLE
Avatar badly metallic in preview window

### ISSUE THREAD

**Issue by kaitas** [mozilla/hubs#2541]
**Description**
Avatar badly metallic in preview window
UnLit, cartoon style avatar, same on mobile.

In the hubs scene, it works fine but in the preview window, it has completely different look. 
It seems a bug in the preview window but it can also be fixed by documentation or good example.
Tell me how to fix it!

My discussion and testing
https://discordapp.com/channels/498741086295031808/715710184575598655/717589055138955307
Same issue by own avatar
https://discordapp.com/channels/498741086295031808/715710184575598655/716447343742025759

The preview is badly metallic! The shader on Blender is 
Texture {Linear, Flat, Repeat, Single Image} -> Background {Color} -> Material Output {Surface}
It is similar shader for UnLit characters.

Here is my test blend and GLB with texture files. Thanks to find any solutions!
https://www.dropbox.com/s/5flnzn4n7wzf9tn/TestAvater20200603.zip?dl=0"

**To Reproduce**
1. Go to 'Set Name & Avatar'
2. Click on 'Browse Avatar'-> 'Create Avatar'
3. Upload own GLB (here is my testing file https://www.dropbox.com/s/5flnzn4n7wzf9tn/TestAvater20200603.zip?dl=0 )
4. See metallic avatar (but the unlit shader works fine in the room)

**Expected behavior**
Preview window must be same with shader in the room.

**Screenshots**
![Issue-Metallic-Preview3](https://user-images.githubusercontent.com/5110708/83596930-e6938780-a5a0-11ea-97b0-72e5a8f231b7.png)
![Issue-Metallic-Preview](https://user-images.githubusercontent.com/5110708/83596928-e5625a80-a5a0-11ea-9690-89bf354bfc14.png)
![Issue-Metallic-Preview2](https://user-images.githubusercontent.com/5110708/83596934-e85d4b00-a5a0-11ea-8bd5-47d25e197cd1.png)

**Hardware** 
(tested by myself)
 - Device: 　Desktop, iPhone
 - OS: Windows, iOS
 - Browser: Chrome on Windows, Safari on iOS

**Additional context**
This model works fine on iOS and Desktop. We need to know how to realize cartoon style in pipeline through Blender->Export->GLB+Texture->Hubs.

![Issue-Metallic-Preview-correct](https://user-images.githubusercontent.com/5110708/83597061-438f3d80-a5a1-11ea-9213-8fbb464e7cdb.png)

Thanks in advance! Akihiko

**Comment by toyakun** [comment]
I'm technical artist in GREE VR Studio with Akihiko.
We're still looking into this issue.

When I imitated "Bot_PBS" material in "AvatarBot_base_for_export.blend" with my eyes, it didn't work.
I named the material "Bot_PBS", added "glTF Settings", and set all image textures.
![image](https://user-images.githubusercontent.com/41459482/86089934-225c3700-bae4-11ea-8bea-ce1ba710021c.png)

However, when I Append and apply "Bot_PBS", it worked.

This solves the problem temporarily, but there is a hassle of setting up a Normal Map etc. if I want to use the Background shader instead of the Principalled BSDF.


When the preview goes unexpected metallic, I can see the error in the console, as shown below.
![コメント 2020-06-30 122138](https://user-images.githubusercontent.com/41459482/86089850-0062b480-bae4-11ea-954d-06757f88f646.png)

When I set Emissive Map or Normal Map
```TypeError: i is undefined```

When I unset Emissive Map or Normal Map
```TypeError: n is undefined```

When I set ORM Map
```TypeError: i is null```

When I unset ORM Map
```TypeError: n is null```


We hope this issue will be solved soon.
(or tell me if we have any mistake/misunderstanding)

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox and Vivaldi

**Comment by netpro2k** [comment]
Thanks for this detailed report! The preview is indeed broken for unlit materials. The preview was designed around our bot avatar and has not really been updated to support all the new avatars people have been creating. It is on my todo list to fix this and a few other issues with preview.

**Comment by kaitas** [comment]
@netpro2k Thanks for your reply.
Do you have any idea for unlit avatars? (In Japanese market, anime style is majority...)

https://github.com/mozilla/hubs/blob/master/src/react-components/avatar-preview.js#L266
If we can find Unlit in this line, we may just set 1.0 or 0 for map to ignore shaders.
I think just we need to set zero to Metallic map (blue channel on ORM).

Tell me your thought.
