### ISSUE TITLE
Support for Google Cardboard "Out of Focus"

### ISSUE THREAD

**Issue by brianlmerritt** [mozilla/hubs#2558]
**Description**
Using Google Chrome on an Android phone with Cardboard installed, I get the option to enter using Cardboard and it seems to work, except the separate images are too far apart.  My VR headset has lens adjustments, but not enough to bring the view into focus.

**To Reproduce**
1. Go to Hubs.mozilla.com with an Android (10) phone with Cardboard app installed and Chrome brower
2. Click on Create room then enter room and select Cardboard VR
3. Attempt to adjust the VR display so objects in left and right eyes appear to be in the same place.

**Expected behavior**
I've tested the cardboard app on my phone (Oneplus 7 Pro) with Google supplied views, youtube, and a few games.  All work.  But not hubs - I can't get objects to focus / line up

**Screenshots**

**Hardware** 
 - Device: OnePlus 7 Pro phone, Destek V5 VR Headset
 - OS: Android
 - Browser [Chrome Brower for Android (latest)

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-204)

**Comment by brianlmerritt** [comment]
![Screenshot_20200611-112149](https://user-images.githubusercontent.com/3381322/84375456-7fe12000-abd7-11ea-80da-18dbf18b7288.jpg)
This is the image, which looks OK, but even though the Destek is adjustable it isn't possible to align left and right images - they remain 2 far apart

**Comment by brianlmerritt** [comment]
Not sure if other cardboard devices are struggling, but I did generate some manual QR codes with varying distance between eye pieces thanks to Destek providing the original measurements and none of them brought the two lens into alignment

**Comment by tbarbette** [comment]
I have the same problem. I have a cardboard that works fine in the cardboard app or other VRs apps. However in google chrome, and with hubs only, the eyes are way too far apart.

**Comment by djay** [comment]
I have the same problem (and the same phone)
if I try https://matterport.com/ I get the same problem. I suspect this is still using WebVR. 
Hubs is supposed to already be converted to WebXR. 
If I view the WebXR demos here - https://immersiveweb.dev/. It has a cardboard settings symbol. If I switch to the Bobo Z6 viewer setting then it doesn't work similar to Hubs. But if I switch to Cardboard view setting then these demos do work.
Hubs doesn't have a setting to switch.
Changing the setting in the Cardboard app doesn't seem to change the viewer in hubs however changing the setting in cardboard app does change the setting with WebXR in immersiveweb examples. 
Is it that Hubs cloud is using WebVR instead of WebXR?

**Comment by djay** [comment]
This has now been fixed in the new UI update. It now seems to be using the proper cardboard settings
However the cardboard button doesn't work so you can't move anywhere.
Also if you click X to close the cardboard mode or change the settings there is now back into it. There should be a "viewer" button to switch I think. I can raise seperate issues for these
