### ISSUE TITLE
Set up github Discussions

### ISSUE THREAD

**Issue by netpro2k** [mozilla/hubs#2636]

**Comment by emclaren** [comment]
Discussions are now live. A few features that would be helpful have not yet been launched because they are not available in the beta version yet. These include: 

1. Categories. Currently, we could only add a hard-coded list of 6 categories (General, Help, TIL, Thanks, Show and Tell, Ideas). These don't really fit with how we plan to use them. Customizable categories will be coming in an upcoming release. I propose

Hubs - Help
Avatars - Help
Spoke - Help
Hubs Cloud - Help 
Show and Tell
Ideas

2. Pin important discussions. Github Discussions has a "spotlight" feature to highlight important topics at the top of the page. Customizing this feature is not yet available on the beta. 

3. Templates - it is not possible to add templates like we currently have for issues. I have mentioned our interest in this  in the Github Discussions beta testing feedback forum. 

4. Stats - There may be user stats available in the future of the beta. These are not publicly available yet.

**Comment by emclaren** [comment]
Proposed template for issues (if the template feature gets added before we can have categories, as this text is sort of "one size fits all") 

**Please share your question**
A clear and concise version of your question. Ex. How do I […]?

**Additional context**
Add any other context about your question here

 <!— If applicable, please provide the following information -->

**Hardware**
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser [e.g. Firefox]

**Screenshots**
Add screenshots that may help to explain your question.

**Hubs Cloud** *(Advanced - for Digital Ocean & Amazon Web Services Users only)*

* Did you read the [Hubs-Cloud Documentation](https://hubs.mozilla.com/docs/hubs-cloud-intro.html)?: [Y/N]
* Question type: [question, bug, feature-request, how-to]
* Relating to: [deployment, admin panel, custom client, spoke, database, app server, streaming server, API, art assets]
* Deployment Type: [Personal 1 server, Enterprise 1 server, Enterprise multi-server, DigitalOcean deploy, N/A]
* Deployment region:
* Do you have a custom client deployed?: [Y/N]
* Do you have custom software/modifications to your servers? [Y/N]

**Comment by emclaren** [comment]
this pull request should add a link to the discussions from the "new issues" tab

**Comment by joshmarinacci** [comment]
Ready to mark  it done?

**Comment by emclaren** [comment]
There is an outstanding pull request related to this, but once it is merged I think we can mark this complete
https://github.com/mozilla/hubs/pull/2685
