### ISSUE TITLE
Character controller causes unnecessary network updates in some cases

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#272]
- When you hit forward on your keyboard briefly, we send out about 20 network updates, most of which are minute changes that occur after the avatar has visibly stopped moving
- When turning with mouse or keyboard, we sometimes send network updates continuously where the avatar's y position is bouncing slightly
- In Firefox, we network hands even when you're not in VR mode, the hands often move slightly even when they're sitting stationary on a table.
See the video for a demo:
https://gfycat.com/MealyUniqueBarnswallow

**Comment by johnshaughnessy** [comment]
Two PR's to address these issues. The first two are fixed by https://github.com/mozilla/hubs/pull/291
The last one is partially fixed by https://github.com/MozillaReality/networked-aframe/pull/6

We still network the hands even when you're not in VR mode, but this will at least stop them from sending updates when they move slightly while sitting on a table.
