### ISSUE TITLE
Spatial sound appears to be coming from the wrong location

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#2855]
This [remixed scene](https://hubs.mozilla.com/scenes/FUFG8yq) contains a spatial audio source co-located with a model of a radio. However, the sound is loudest on the boardwalk several metres away from the source.

Tested on:

- Chrome Version 85.0.4183.59 (Official Build) beta (64-bit) on MacOS
- Firefox 79.0 (64-bit) on MacOs

**Comment by InfiniteLee** [comment]
@rawnsley can you mark your scene as remixable so we can look at how it setup in spoke?

**Comment by rawnsley** [comment]
@InfiniteLee Done (same link).

**Comment by johnshaughnessy** [comment]
I was able to reproduce this error (in Firefox and Chrome) using the scene provided. Here is what I noticed:
- The audio played from the world origin (0,0,0) - it was loudest at this spot and only this spot. (It was not equally loud at a radius around the radio where the audio node was placed.)
- The audio came from the radio correctly when I forced use of `Audio`s instead of `PositionalAudio`s by using `/audiomode`

My guess right now is that audio nodes from spoke are sometimes initialized to come from the scene origin, but I have not been able to figure out why

**Comment by johnshaughnessy** [comment]
Ok so what's happening is something like : 
An audio node gets created, but since its `object3D` is not `visible`, `updateMatrixWorld` is not taking effect, and the audio ends up with a default matrix (at the origin).
Looking for a fix.
