### ISSUE TITLE
Waypoints do not seem to always be releasing their occupant

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs#2897]
**Description**
When I use a waypoint, sometimes it seems like the waypoint occupancy isn't cleared even when I leave the spot. This was also happening in standup last week, but I'm seeing it very clearly with a new room that uses the new feature introduced in #2837.  However, this was reproducing with the waypoints previously when they were accessed their usual way (we saw this in the classroom scene at the time). 

Repro scene here: https://hubs.mozilla.com/4ukSx32/glossy-eager-terrain

**To Reproduce**
1. Enter the room linked above
2. Click on the 'Visit Room' link on the signpost. This is just a link to the same room, with the waypoint specified via anchor, so you will teleport to the overlook
3. Leave the overlook by using the WASD keys and/or teleporting back to the main crater 
4. Try to click the 'Visit Room' link to teleport back up to the overlook
5. Observe that it no longer works. Refreshing fixes this, so presumably the waypoint still seems to believe that I'm occupying the space. 

**Expected behavior**
I am able to return to the waypoint

**Hardware** 
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox

**Comment by johnshaughnessy** [comment]
There are two separate issues here:

For hash-based teleportation like the one linked in the room above (related to #2837 ) is that the teleportation only happens when the hash is updated: https://github.com/mozilla/hubs/pull/2837/files#diff-094b64826e418f176749a3c13da093a1R328 This means that if you teleport with the hash, then try to teleport with the same hash, it won't work the second time. We can fix this by either clearing the hash on teleport or changing the check on the line linked above.

The issues we were seeing in the school space are different, and seem to have something to do with not properly unoccupying  waypoints when rapidly transitioning between them. I don't have a clear idea of how to fix this.
