### ISSUE TITLE
redirect static assets' URLs to hashed URLs

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#316]
it'd be nice if https://assets-prod.reticulum.io/assets/images/logo.svg (or https://hubs.mozilla.com/assets/images/logo.svg) redirected to the latest version of the asset (whose filename has the most recent content hash) -> 
https://assets-prod.reticulum.io/assets/images/logo-8f1dfd234d060073524bc29912a24f75.svg

this is useful for things like referencing URLs in `<meta>` tags (for Twitter/Facebook/Pinterest/etc.) and paths in `icons` + `screenshots` in a Web-App Manifest (adding in issue #274).

let me know if using Webpack plugins to rewrite the HTML + JSON is preferred. and I can close this issue, assuing there's not another use case for this.

**Comment by gfodor** [comment]
We've avoided having non-digested URLs on cloudfront domains (to improve caching/remove the need for manual cache invalidation) so for fixed URLs as an explicit copy step and serve it directly from the ALB (which won't be edge cached.) This is what we do with `favicon.png`.

It's preferred however that we edge cache as much as we can, so using the digested filename + updating webpack to pack it in properly is probably the best way to do it.

**Comment by gfodor** [comment]
Oh, and in terms of having non-digested URLs redirect to the digested variants, I don't think we want to do that because if we implemented that now, it would further couple reticulum with the client bundle (since reticulum would have to have redirection logic that incorporated a map of digest shas.) The mid-term plan is to remove the client from the reticulum habitat package and have a s3-backed origin, with server side templates for the root html files. That is gated on us moving the a-scene into react.

**Comment by cvan** [comment]
thanks for the helpful notes. if I understand this correctly, I still am not sure how paths to assets will be defined in the HTML templates, SAAS stylesheets, web-app manifest, and JS files.

would this involve rewriting the URLs in reticulum? there is also a popular S3 plugin for Webpack: https://github.com/webpack-contrib/s3-plugin-webpack
