### ISSUE TITLE
Halloween scenes - Catacomb

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/hubs#3186]
**Description**

The scene is very bright and not very Halloween-like. Please see attached screenshot.

**To Reproduce**
1. Go to Catacombs Hubs scene

**Expected behavior**

The scene to be darker and creepier

**Screenshots**
![filename](https://user-images.githubusercontent.com/31939113/96305013-13e34e00-0ff5-11eb-8d63-e47392e0d18c.jpg)

**Hardware** 
 
-  Device: Pico Neo 2
-  OS: Pico Android
-  Browser: FxR 12

**Additional context**

**Comment by Softvision-GeluHaiduc** [comment]
This scene is rendered differently on Firefox Release 81.0.1 and Chrome 86.0.4240.75 on both Windows 10x64 and Ubuntu 18.04.2.
 
![image](https://user-images.githubusercontent.com/51400741/96442524-ef18f180-1213-11eb-90e2-5296443baef0.png)

**Comment by misslivirose** [comment]
This is due to the fact that VR devices default to a different level of quality that does not use dynamic lighting. Ideally the scene content would have the lighting baked in, but this is to be expected for what Hubs shows. Changing the material quality level from "high" to "low" reproduces this, but it's expected since we're turning off the lighting, as I understand it.

**Comment by brianpeiris** [comment]
I would consider this an issue with the environment art, not a bug in Hubs. Ideally, lighting and shading would be baked into this scene as Liv mentioned, so that it renders as desired on mobile/standalone devices.
