### ISSUE TITLE
Scene failed to load

### ISSUE THREAD

**Issue by jessicasymons** [mozilla/hubs#3260]
**Description**
Tried to open hub several times on Samsung S2 tablet and on iPhone

Each time, received message 'Scene failed to load'

**To Reproduce**
1. Go to https://hubs.mozilla.com/m6hDQPe/ using phone or tablet
2. . See error

**Expected behavior**
Hub loads

**Screenshots**

**Hardware** 
 - Device: Samsung S2 / iPhone
 - OS: Android / iOS
 - Browser Samsung Internet / Safari

**Additional context**
This hub has some v large assets in it but it does work on some devices e.g. Samsung Galaxy S9
![Screenshot_20201031-224134](https://user-images.githubusercontent.com/54954604/97791536-43847f80-1bcb-11eb-8b39-030c18e9bc6b.png)

**Comment by misslivirose** [comment]
This didn't reproduce for me on an iPhone 11 Pro, but I suspect that this is because the scene is much larger than we recommend for accessing on phones/tablets. There are 40 textures and 713,188 triangles, both of which can contribute to performance problems. The recommended polygon count for mobile devices is 50,000 triangles. It looks like this floor on this room was created by pasting a lot of images into the Hubs room - there might be a performance improvement that can be made by using Spoke to place a textured floor, rather than having them all be added as separate images, and the publishing workflow in Spoke will do a performance check on the scene. 

I'm going to convert this to a discussion so that folks can chime in with additional suggestions for optimization for this particular room/scene.
