### ISSUE TITLE
Big avatar doesn't let you see

### ISSUE THREAD

**Issue by Yajo** [mozilla/hubs#3403]
**Description**
If your avatar is big enough, such as the ones you generate in https://fullbody.readyplayer.me/ (which are really cool), you can't see fine.

**To Reproduce**
1. Go to https://fullbody.readyplayer.me/
2. Generate one avatar
3. Use it in a hub.
4. You can't see!

**Expected behavior**
My avatar should be invisible to myself, unless when mirrored.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/973709/99799435-8f6f7800-2b2a-11eb-92a5-3cca54329f3c.png)

**Hardware** 
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox

**Comment by misslivirose** [comment]
The avatar format for Hubs makes the head of avatars invisible to the wearer, but it's an intentional design decision to ground the user by showing the rest of the body when they look down and not just make the whole avatar invisible. For avatars to work properly in Hubs, they need to use the specific avatar skeleton that works with the Hubs camera rig, which is documented [here](https://d1a370nemizbjq.cloudfront.net/b62e97f0-eae6-4327-bb22-e6bf1b1039bb.glb). Full body avatars are not currently supported, and a look at the .glb files in blender tells me that this type of avatar isn't using the hierarchy we expect for avatars (which is not an error on their part; different platforms have different avatar requirements and this one just isn't one that is compatible with Hubs at this time). The head-only readyplayer.me avatars are the ones that currently work with Hubs.
