### ISSUE TITLE
Textures Appear outlined, and no Lightmap Appears in Spoke

### ISSUE THREAD

**Issue by Whystler** [mozilla/hubs#3441]
I followed the video Dom   and Jim  did .  And this was my result in Spoke (no lightmap)... any advice?

Picture illustrates issues.

Zip contains: glb, and blender files.

![LightSpokeTesting-screen01a](https://user-images.githubusercontent.com/57971134/100551944-efb09900-3251-11eb-81f5-1b04859d7ecb.png)
[TestLighting.zip](https://github.com/mozilla/hubs/files/5612755/TestLighting.zip)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-499)

**Comment by Whystler** [comment]
Followup:

-While the screeshot above shows spot in Unlit mode, the shadows also do not show in Lit mode.
-the black bordered textures only appear in Unlit.  
-I also noticed that the number of materials and textures in Spoke is shown to be 3.  I'm not sure if the lightmap is imported as an additional texture that is noted in Spoke or not, but in this case it doesn't show up.  The three textures/materials would be: stone, wood, and velvet in this case.

![LightSpokeTesting-screen02a](https://user-images.githubusercontent.com/57971134/100635459-8d61a200-32fe-11eb-8be3-f9d8da65a9ac.png)

**Comment by cvanmeurs** [comment]
Thanks for all the info.  I'll be taking a look at this today.

**Comment by cvanmeurs** [comment]
Can I get a version of the .blend file with the textures packed into the file?

Go to File > External Data > Automatically Pack Into .blend, then re-save.

**Comment by Whystler** [comment]
Here you go.  And thanks.  I'm especially worried it's a stupid little mistake I overlooked, but I went over the process a few times.  
[TestingLighting01aaa.zip](https://github.com/mozilla/hubs/files/5624466/TestingLighting01aaa.zip)

**Comment by cvanmeurs** [comment]
No worries; I make those all the time.  Especially bouncing back and forth between avatars and environments - there's a lot of little nuanced details to try to remember.

**Comment by cvanmeurs** [comment]
Well I'm not sure what to say, but as you can see from my screenshot below, your scene imported properly to Spoke on my first attempt with no changes to your scene at all.  

What version of the Hubs Exporter are you using?  I seem to be using version 0.0.4.  Also make sure when you export your GLB file that you have the box checked for "Include > Custom Properties" and "Extensions > Hubs Components".  Without these selected, the lightmaps won't work.

I did, however, notice an issue with your lightmap UV's that likely account for the black lines you were seeing.  Your UV islands in your Lightmap UV channel have ZERO gap between them.  You're going to want to pack your lightmap UV's so that there's sufficient gap between the islands, and I recommend that you use a margin of at least 4-8 pixels when you are baking; this is in the Bake settings in Blender.  This will add some additional bake info beyond your UV island borders, so that any split pixels that may occur have lighting data and not the black background behind the baked lighting data.  

![spoke-import](https://user-images.githubusercontent.com/63256260/100780677-de38cf80-33be-11eb-8248-d386fbbdf580.png)

**Comment by Whystler** [comment]
Well, would you look at that ...

Ok, I will go back and check custom properties and extensions business.

Regarding the black lines ...

Definitely, I'll take your point about my islands being too close, and will take steps to fix that - but I will say that I'm skeptical that this has anything to do with the black lines in question.  They only showed up in Unlit Mode in spoke.  And I don't see them in your screenshot at all.  Also, most importantly, they appear around each tile of the tiled textures.  And these textures are not on the Lightmap layer (if it's called a layer).

It's really important to me overall that you know how much I appreciate you taking the time to check this out.  I've been wanting to try out the new lighting map layer for months.  It just seemed daunting and other shiny things took my attention away.

I'll update you on the progress later this aft.

**Comment by Whystler** [comment]
Oh dear ... still no lightmap for me.  It looks the same as the first screenshot I put up.

I did not originally have the "include, custom properties" checked.  I did this time.

I -did- originally have the "extensions, Hubs Components" checked.

Here is a screenshot from Blender (showing that I have things checked for export) , and a screenshot from Spoke (showing some information from the "verify gltf" tab, if it's any help ...

![LightSpokeTesting-screen03a](https://user-images.githubusercontent.com/57971134/100795132-90d35700-33ec-11eb-808b-9921cbb66882.png)

![LightSpokeTesting-screen04a](https://user-images.githubusercontent.com/57971134/100795140-94ff7480-33ec-11eb-93ea-8b5d9dbc0d67.png)

**Comment by Whystler** [comment]
Also, this is my scene hierarchy from Spoke.  It looks somewhat different than yours.  I'm particularly interested that it's missing something you have called the "scene preview camera".  Could that have something to do with it?

![LightSpokeTesting-screen05a](https://user-images.githubusercontent.com/57971134/100795790-9e3d1100-33ed-11eb-977c-f030f1622ee8.png)

**Comment by matthewbcool** [comment]
Blender version 2.91?

**Comment by Whystler** [comment]
Yes, I'm using Blender 2.91.0  ... It's funny that you asked, because I was just coming back here to report that lol.

**Comment by Whystler** [comment]
I noticed the Hubs section in the Blender material properties tab.  So I decided to check it out.  I used it to add each of the three materials in the model as components (as shown in picture).  It also did not work.

![LightSpokeTesting-screen06a](https://user-images.githubusercontent.com/57971134/100797360-fd038a00-33ef-11eb-92cf-b9baa365c6b4.png)

**Comment by Whystler** [comment]
@cvanmeurs - Would you be able to send me a copy of your altered blender file, and also your spoke file, so I can check and see what differences there may be?  Or if your files don't show me your results, then it's a different problem altogether on my end.

**Comment by cvanmeurs** [comment]
I didn't alter your Blender file at all.  I only plugged the lightmap into the diffuse channel to make sure they were showing up, then I plugged the diffuse textures back in, looked at your UV's, and then exported.  But I can send you the exported GLB file.  1 sec.

**Comment by cvanmeurs** [comment]
[TetsingLighting01aaa.zip](https://github.com/mozilla/hubs/files/5625821/TetsingLighting01aaa.zip)

**Comment by rawnsley** [comment]
In case it's relevant, someone is reporting an export problem with lightmaps in Blender 2.91 on Discord :

> Hmm, noticing the latest version of Blender (2.91) broke the MOZ_lightmap node (doesn't seem to export lightmaps anymore). Any plans for updating this? For now I'll stick to 2.90.

**Comment by Whystler** [comment]
Well that would definitely explain the problem.  Are you using 2.90 @cvanmeurs ?

**Comment by cvanmeurs** [comment]
Yikes, no, I'm using 2.90.0.  Good to know tho.  When did 2.91 get released?  @netpro2k will need to update the exporter to support the new version.

Sorry about that, I didn't even realize there was a new Blender release.

**Comment by cvanmeurs** [comment]
Thanks @rawnsley for pointing that out.

**Comment by Whystler** [comment]
Well at least I don't have to worry it was because it was just my absent brain lol.

I have questions about the exporting of Lightmaps.  I am noticing for certain now that the Lightmap is in fact washed out compared to the result in blender.  I think it would be amazing if the next time the exporter is tweaked.  Could there could be a slider to increase that intensity beyond the max that it is now?  Or even if you allowed the LightmapUV to be "on top" of the textureUV map and completely opaque.  And then we could make sure that our light baked texture is a PNG file with transparency where the light shows through?

Should these questions stay here or go somewhere else?

**Comment by cvanmeurs** [comment]
Technically we try to keep these on the 'Discussions' page, but this works.  That's why I couldn't find this thread originally.  I actually didn't even realize there was a separate 'Issues' page until today.  I don't use GitHub much...

I know what you mean about the lightmaps looking washed out.  It's frustrating.  You can try messing with the Lightmap Intensity value in the Blender node, but I have not really gotten good results out of that myself.

One way to work around it is to just multiply your lightmap on top of your diffuse texture, and not use the Lightmap node at all.  Or, like I did for the Haunted Garage scene, I just baked all of my lighting and textures into a single diffuse texture - I lost some resolution, but I got much darker darks that way.

**Comment by Whystler** [comment]
That's what I used to do for certain.

**Comment by brianpeiris** [comment]
Looks like there isn't an actionable issue to be resolved here. If there is still a compatibility issue with the latest version of Blender, perhaps a new bug should be opened on the hubs-blender-exporter repo: https://github.com/MozillaReality/hubs-blender-exporter/
