### ISSUE TITLE
Enable cardboard mode on iOS

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#352]
For those who are brave enough for it, we should allow entry into stereoscopic mode on iOS (with the usual treatment of having it as a secondary option.)

**Comment by InfiniteLee** [comment]
Currently working in https://github.com/mozilla/hubs/tree/fix/ios_cardboard_support, however cardboard mode in iOS currently looks like this:
![image uploaded from ios](https://user-images.githubusercontent.com/1821537/39550381-ea99426e-4e15-11e8-9d4c-d96a719534dc.png)

**Comment by InfiniteLee** [comment]
The problem is only partly that the url bar doesnt go away: It seems like some 2d ui element is not being removed and blocks your view (which is why you see white in that screenshot). Also, you can't actually do stereo rendering when you use that shortcut trick because it causes the page to be loaded in a webview.

**Comment by cvan** [comment]
@InfiniteLee I notice that the URL bar does not appear on load, because of the `<meta aframe-injected="" name="mobile-web-app-capable" content="yes">` tag that A-Frame injects into the `<head>`:

![image](https://user-images.githubusercontent.com/203725/39788318-c1964470-52de-11e8-89b4-b80df440c2a7.png)

but when you navigate to another page, Safari bumps the URL bar up again. if you do an orientation change, rotating your iPhone from horizontal to vertical and back to horizontal, you'll notice the URL bar disappears, as expected.

re: the webview issue (#181): any clues of how to remotely debug to figure out what errors are happening? (my currently theory is the click regions are off, causing the clicks to not trigger properly.)

**Comment by InfiniteLee** [comment]
I seemed to have gotten my wires crossed about the webview thing (being in a webview has nothing to do with not being able to use stereo, but I do currently see an issue where I can't click "Enter on Phone"). But my point with _this_ issue has less to do with the url bar and more to do with the fact that white is drawn on top of everything in the view. And sorry, I don't think I know anymore about remote debugging than you do.

**Comment by j-conrad** [comment]
Not sure if this is useful, but the URL bar goes away using Hubs on my iPhone 6s (up to date OS).
I saw on another iPhone X that it exhibits the behavior you showed above. Not sure why they’re different except that perhaps on the X screen, because of its dimensions it may always show. Can you make it go away on other sites (non-video)?

**Comment by rugk** [comment]
BTW also needs to be enabled in Firefox for Android: https://github.com/mozilla/hubs/issues/392

**Comment by brianpeiris** [comment]
We've discussed this and we only intend to support Cardboard in Chrome for Android, since the gyroscopic lag makes for a terrible experience on iOS.

**Comment by deemeetree** [comment]
Any news on that? Supporting Mozilla hubs on iOS?

**Comment by brianpeiris** [comment]
@deemeetree To be clear, we do support Hubs on iOS through Safari, but we do not support Cardboard mode. This is unlikely to change unless Apple decides to implement the WebXR standard at some point.

**Comment by deemeetree** [comment]
@brianpeiris why is it needed?

**Comment by brianpeiris** [comment]
As I mentioned above, WebVR apps currently emulate Cardboard mode with the browser's motion sensor APIs, but the experience is really bad because those APIs were not meant to be used for VR. Those sensor APIs are not precise enough and/or do not update often enough, so as a result, using an app in a Cardboard headset is very nauseating.

**Comment by robinzhx** [comment]
Is there any way to have a customized app allowing people with iOS be able to use a cheap cardboard solution to view Hubs in VR? We currently have a class of students that might need a quick solution. We host a Hubs Cloud in AWS, and I am willing to develop a safari-like or WebXR iOS app for a small group of people to just test it using TestFlight. Is it even possible?

**Comment by GBR-422777** [comment]
Is this issue still persisting on iOS? any timeline to solve this or idea if the feature has been adopted?

**Comment by jywarren** [comment]
This recent-ish (may '22) article hints that it could be in an upcoming iOS release, but it might instead also be related to their headset project: https://www.protocol.com/entertainment/apple-webxr-ar-ios-iphone
