### ISSUE TITLE
Viewport is resized when sidebar is open and pause menu is opened

### ISSUE THREAD

**Issue by robertlong** [mozilla/hubs#3524]
**Description**
This bug was reported by @robinkwilson 

**To Reproduce**
1. Open the chat sidebar
2. Open pause menu
3. The canvas viewport shrinks

**Expected behavior**
The canvas should always be resized to the size of the viewport

**Comment by brianpeiris** [comment]
Probably the same bug, but I also see this happen when the sidebar is closed.

**Comment by brianpeiris** [comment]
To add more detail, I see this happen in Firefox on Windows. If I resize my browser window, the rendered viewport squeezes horizontally, and then when I press the spacebar, it stretches back horizontally.

**Comment by Softvision-GeluHaiduc** [comment]
I verified this issue using Firefox and Chrome on Windows 10 and Ubuntu 20.04.1
The main issue reported is fixed but unfortunately, the scenario depicted by Brian in the above comment is still reproducible on Chrome on both Windows and Ubuntu, the issue is not reproducible on Firefox.
[Here](https://drive.google.com/file/d/1sdJ3NYx19wdzEP6Qg_ocbiyiDNBoJJtE/view?usp=sharing) is a video of the issue.

**Comment by robertlong** [comment]
@Softvision-GeluHaiduc I think this should be fixed in all browsers now

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using Firefox and Chrome on Windows 10 and Ubuntu 20.04.1
Now, the viewport is not resized when the sidebar is open and the pause menu is opened, the scenario from Brian's comment is also fixed.
