### ISSUE TITLE
Add gamepad support for browser-only mode

### ISSUE THREAD

**Issue by bookmunkie** [mozilla/hubs#364]
Click-and-drag to look around is quite awkward

**Comment by cvan** [comment]
I have basically a warehouse of USB and Bluetooth controllers to test with. Xbox, Steam, Nintendo 64 (unofficial), SNES (unofficial), NES (unofficial), Sega Genesis (unofficial), Nintendo Advantage, and several Logitech gamepads.

Which gamepads do you have, and perhaps ones that others are interested in using?

Reason I ask is because, if this feature request gets suppor, there is some button mapping magic that would have to be in place in order to provide a consistent, expected experience for gamepad users.

Thanks for filing!

**Comment by bookmunkie** [comment]
You're welcome, and thanks for your reply.

Personally, I'm most concerned with USB Xbox gamepads like the Afterglow AX.1 and Logitech F310.

**Comment by robertlong** [comment]
Support should land in https://github.com/mozilla/hubs/pull/629
