### ISSUE TITLE
Replace our Three.js fork to the official one

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4108]
We Hubs team have [our Three.js fork](https://github.com/MozillaReality/three.js) but maintaining it is costly and sometimes it is hard to bump into the upstream Three.js.

So we have been wanting to replace our fork to the official one by removing our specific code from Three.js as much as possible.

As far as I know the left tasks for the replacement are

Hubs (and Spoke?)
- [ ] How to keep WebVR support. Three.js has dropped WebVR support and focuses on WebXR. But some major web browsers don't support WebXR (by default) yet, eg. Firefox. So we want to keep WebVR support. Probably importing [webxr-polyfill](https://github.com/immersive-web/webxr-polyfill) may be a solution?
- [x] Rewrite our special glTF extension handlers in Hubs glTF loader to the ones with the Three.js glTF loader plugin system #4117
- [x] Multiview Support. Three.js has dropped multiview support because anti-aliasing with multiview is still unusable and it's useless. Is it ok for us to drop the support, too?
- [x] Remove regular `Geometry`. Three.js has dropped regular `Geometry` and it supports only `BufferGeometry`. If we use `Geometry` we need to replace it with `BufferGeometry`. At least it seems we need to update [three-pathfinding](https://github.com/donmccurdy/three-pathfinding/commit/b458c4087eb83bff11ecfff6539b2e2cbb3ae472)
- [x] Figure out what patches we have applied to our Threejs fork
- [ ] Figure out which patches we need/want to keep
- [x] Figure out the easy way to apply our patches (the ones we want to keep or future ones) to Three.js https://github.com/MozillaReality/three.js/wiki/Modifications-on-top-of-three.js Thanks @brianpeiris 

Spoke
- [ ] UBO support. [three-batch-manager](https://github.com/mozillareality/three-batch-manager), used in Spoke (and future Hubs?), uses UBO but Three.js UBO PR has not been merged yet. And it seems we added some changed from the PR.
- [ ] Rewrite the special loader/exporter for Spoke to the ones with the Three.js glTF loader/exporter plugin system (if possible)

Related: https://github.com/MozillaReality/three.js/pull/47

Feel free to update the task list if you have anything else.

**Comment by brianpeiris** [comment]
Here's a link to my documentation about the patches we've applied in our fork: https://github.com/MozillaReality/three.js/wiki/Modifications-on-top-of-three.js

**Comment by takahirox** [comment]
As we discussed in Discord before I would like to suggest to drop Multiview support. Any objections?

And I speculate that the official Three.js would support Multiview extension if Multiview + Anti aliasing will be supported by major browsers and the extension will be more practical. If that happens we will be able to support Multiview again without changing our code by just importing the Three.js.

**Comment by takahirox** [comment]
From @brianpeiris 's note https://github.com/MozillaReality/three.js/wiki/Modifications-on-top-of-three.js, I'm looking into which patches we should keep and how we should apply.

I'm focusing on Hubs Client and low prioritize Spoke specific stuffs for now. I keep updating this comment.


* VAO support:
  * Diff: https://github.com/MozillaReality/three.js/compare/patch-001-ubo...patch-002-vao
  * Source PRs:
    * https://github.com/MozillaReality/three.js/pull/37
    * https://github.com/mrdoob/three.js/pull/16287

VAO is in the latest Three.js. We would be able to simply drop this patch.

* GLTFLoader createParser:
  * Diff: https://github.com/MozillaReality/three.js/compare/patch-002-vao...patch-003-createParser
  * Source PRs:
    * https://github.com/MozillaReality/three.js/pull/2

I remove the dependency with `createParser()` in #4117 so we would be able to simply drop this patch.

* KTX and Basis:
  * Diff: https://github.com/MozillaReality/three.js/compare/patch-003-createParser...patch-004-ktx-basis
  * Source PRs:
    * https://github.com/MozillaReality/three.js/pull/51

The latest `GLTFLoader` supports KTX and Basis support is achieved with the plugin system in #4117. We would be able to simply drop this patch.

* Miscellaneous:
  * Diff: https://github.com/MozillaReality/three.js/compare/patch-004-ktx-basis...patch-005-misc
  * Source commits and PRs:
    * https://github.com/MozillaReality/three.js/commit/f3115d3239d1aa045a64a1c82cf459e
    * https://github.com/MozillaReality/three.js/commit/d83c538124aa603ad2cd6dda1ada520
    * https://github.com/MozillaReality/three.js/pull/8
    * https://github.com/MozillaReality/three.js/pull/10
    * https://github.com/MozillaReality/three.js/pull/21
    * https://github.com/MozillaReality/three.js/pull/23
    * https://github.com/MozillaReality/three.js/pull/29
    * https://github.com/MozillaReality/three.js/pull/32
    * https://github.com/MozillaReality/three.js/pull/39
    * https://github.com/MozillaReality/three.js/pull/40
    * https://github.com/MozillaReality/three.js/pull/43
    * https://github.com/MozillaReality/three.js/pull/44
    * https://github.com/MozillaReality/three.js/pull/46

WIP...

**Comment by netpro2k** [comment]
> I'm focusing on Hubs Client now and would like to think of Spoke next time. (This means we would import the official Three.js for Hubs while we would import our fork for Spoke for a while...)

Yep that seems like the right order of operations.

> VAO is in the latest Three.js. We would be able to simply drop this patch.

That sounds right to me. I don't think we modified this. Pretty sure we also imported the UBO patch but we made a bunch of changes to it. I don't see that in this list. The only thing using either of these as far as I am aware is the dynamic batching code in three-batch-manager, but we currently have this disabled in Hubs. It is used in Spoke though to make the architecture kit perform reasonably, without it things sort of crawl when lots of kit pieces are used. We disabled it in Hubs since we ran into compatibility issues on some devices and our current atlasing algorithm is quite memory hungry.. but would like to get it working again someday.

> I remove the dependency with createParser() in #4198 so we would be able to simply drop this patch.

Awesome, that sounds good.

> The latest GLTFLoader supports KTX and Basis support is achieved with the plugin system in #4198. We would be able to simply drop this patch.

Will review the PR on its own, but at a glance its looking good. And yeah the KTX stuff in our threejs fork is just directly backported from upstream, the only change was in the gltf loader to handle our (deprecated) custom extension, but you handled that in this PR.

> Diff: MozillaReality/three.js@patch-004-ktx-basis...patch-005-misc

I see a bunch of different changes in here:

**GLTFLoader**
- add revokeObjectUrls as an option to (prevent?) object urls from being cleaned up... I don't see where we are using this and not sure why we would want it...
- Clearing the cache after parse... I think that had to do with how we were splitting the parsing step up so that we could do things like apply our extensions. I don't think this would be needed anymore since we are now handling it with the plugin system.
- uv2s change... Pretty sure this is backporting a bugfix from upstream so it can be dropped
- RGBA check... Looks like this is handled in upstream GLTFLoader, and in a better way, so we can drop this.
- use UUID instead of prefering name for animation targets... This still seems like the correct behavior to me since the GLTF spec does not guarantee unique names.. I am curious to know if you were able to find out why this is being done this way in the upstream repo? I know there are issues with cloning animations with uuid targets, but that also seems like a bug.

**PlaneGeometory**
- Adding flipy... We do this since threejs assumes this is true for all its built in geometry but we turn this off on our texture loader since createImageBitmap in Firefox does not support flipping. As you suggest we can do this external from PlaneGeometry. It only a handful of verts so the duplicate work should not really be an issue.

**Mesh**
- Support for raycasting against TriangleStip meshes... This was added to be able to put menus on things drawn with the pen tool which originally used triangle strips. Since triangle stip support was dropped the pen tool was already updated to not use them, so this should be safe to drop as well.

**WebGLRenderer**
- Flag to force webxr?.. It seems we wanted this to continue using WebVR in some browsers but I don't really remember why. Like you suggested I think this goes away if we just always use WebXR, providing backwards compat using the polyfill.
- Always upload video textures at the start of the frame on Oculus browser.... I dont remember the exact detail here but I remember we added this because video textures would flicker on oclusu browser when using multiview. It apparently also was a performance hit even when not using multivew. We had gotten feedback from the Oculus browser team that this would fix our issue (I will forward you the email chain about this). We are no longer using multiview, and Its very possible/likely that this is no longer needed, so I would be ok with dropping this solong as we take extra care to test videos on Oculus browser (maybe with and without it?)
- Better handling of deprecated arguments to render ... The common wisdom seems to be that using `arguments` creates garbage, but I havent really found anything recent indicating if this is still true in modern engines or is just a carry over. Like you suggest if it is still an issue it should probably land upstream as well...

**WebGLProgram**
- Fix deinfes for RawShaderMaterial... I forget the exact context for this, but I think it had something to do with using material.defines in RawShaderMaterials not compiling when using WebGL 2 because they ended up being inserted before the `#version 300 es` declaration, which *HAS* to be the first line for the shader to compile. We should be able to easily test this. Also possible its since been fixed upstream, and if not is probably a reasonable PR for us to submit

**WebVRMnager/WebXRMnager**
- Add getCameraPose... It looks like Diego made this change, I am pretty sure its something aframe is using. We need to either keep this or figure out a way to modify our aframe fork to handle it (or find out if we no longer need it)
- setPoseTarget... Like you pointed out, it does not seem we are using this.. Its mentioned here https://github.com/mozilla/hubs/issues/438 but does sound like its no longer an issue? John might have an idea since he reworked a lot of the player camera stuff at some point.

> I think this can be achievable with WebGLRenderer.compile() and WebGLRenderer.initTexture() even without hacking the renderer.

I think initTexture did not exist when we originally created this patch. As documented it seems like it does the main thing we were trying to do here, prevent hitching when first uploading textures.

> Regarding parser.cache.removeAll(), I move it in the plugin in #4198 so we can drop this change.

That sounds good.

> Regarding the changes of TextureLoader, can't we create our custom loader? Or is this the change for TextureLoader used in certain Three.js modules?

I think we did it that way to ensure everything always used the ImageBitmapLoader since it made such a big performance impact. I suspect there are still things in afame that arent using our custom loader but we would have to test and find out. I am ok ditching this in favor of a custom loader solong as we can make sure nothing is using the default TextureLoader.

> The exporter changes are only for Spoke

That seems correct yes. The only thing I am aware of using the exporter in Hubs is saving of drawings, but those have no maps.

**Comment by brianpeiris** [comment]
Thank you both for doing a through review of the patches. I've added my notes below (sorry some of it is just repeating Dom's notes).

- I agree we can drop the VAO patch
- I agree we can drop createParser
- I agree we can drop KTX Basis patch
- Using compile and initTexture sounds about right
- Unsure about the RawShaderMaterial change, but we do use ShaderMaterial and RawShaderMaterial in Hubs, lib-hubs (you might not have know about this repo), and Spoke, so we'll want to make sure these things don't break
  - https://github.com/mozilla/hubs/search?q=rawshadermaterial
  - https://github.com/mozilla/hubs/search?q=shadermaterial
  - https://github.com/mozillareality/lib-hubs/search?q=rawshadermaterial
  - https://github.com/mozilla/spoke/search?q=shadermaterial
- Looks like getCameraPose is only used in a-frame's look-controls, which I don't think we use in Hubs, so it should be safe to drop.
- setPoseTarget should no longer be necessary, but we should confirm once we test with webxr-polyfil.
- I'll defer to Dom regarding TextureLoader/ImageBitmapLoader and PlaneBufferGeometry.
- Can you point out where you've implemented a plugin for `parser.cache.removeAll()`? I don't see it in #4198
- My understanding about `arguments` is that JS engines will consider the function more dynamic than usual and it will cause the optimizer to bail on the function. This might be outdated knowledge though. Here's an old article about it: https://github.com/davidmarkclements/v8-perf#leaking-and-arrayifying-arguments. Glad three.js accepted the PR for this so quickly though, nice one!
- The GLTFExporter changes regarding image export were probably only for Spoke, and in any case, I reverted the exporter patches when I last upgraded three.js. Spoke now has its own custom GLTF exporter implementation, so we can ignore this, but obviously we'll have to figure out what to do with Spoke's GLTF code separately.
- I'm not familiar enough with video texture uploading, so I'll defer to you and Dom on this.
- Regarding the animation target UUIDs, I'm not familiar with the codepaths here, so I'll defer my opinion. We should certainly test the affected features though. The exporter code is again probably only for Spoke, so it makes sense to leave that until we are ready to upgrade Spoke.
- The drawing tool was changed to use indexed triangles in https://github.com/mozilla/hubs/pull/2992, so it should be fine to drop the raycasting patch
- webxr-polyfill will probably make the forceWebVR flag obsolete, but we'll need to confirm. We used this flag for firefox reality in particular.
- Unsure about the transparency/texture format fix. I'll defer to you, but I imagine it will be easy to test if this is broken.

**Comment by takahirox** [comment]
Thanks for the comments.

I have one thing I want to discuss. `ImageBitmap` support on Firefox.

In the latest Three.js, it forces to disable texture default color space conversion.

https://github.com/mrdoob/three.js/pull/21336

I think it's a right direction as web 3d graphics engine. And glTF spec requires no color space conversion.

For `ImageBitmap`, no color space conversion option needs to be specified on creation (because it's decoded on creation). Then the latest `GLTFLoader` forces `colorSpaceConversion: 'none'` option to `ImageBitmapLoader`.

But Firefox has a problem. If option is passed to `createImageBitmap()` it fails because of Firefox bug. So the latest `GLTFLoader` disables `ImageBitmap` for Firefox.

I think we have two options for `ImageBitmap`.

1. We follow the Three.js default configuration, disables `ImageBitmap` for Firefox. Pros: We don't need apply a patch or don't need our fork. Cons: Firefox won't get the benefit from `ImageBItmap` that is texture upload time for `ImageBitmap` is much shorter than regular image. If we don't prioritize Firefox, we might accept this disadvantage?

2. We drop the `colorSpaceConversion: 'none'` option for `createImageBitmap()` and enable `ImageBitmap` even for Firefox. Pros: Firefox users keep getting the benefit of `ImageBitmap`. Cons: We may need to apply a patch or make a Three.js fork. And if image file includes ICC profiles the render results can be wrong.

Personally I prefer 1 because I guess there may not be so many Firefox users.

**Comment by netpro2k** [comment]
Just for completeness, I would propose an "option 3:
3. We always use `createImageBitmap()` but drop the `colorSpaceConversion: 'none'` option only in Firefox. Pros: Firefox users keep getting the benefit of `ImageBitmap`. Cons: We need to maintain a fork (or convince upstream this is a good idea). Render results may look wrong in Firefox.

Since we will likely be maintaining some amount of patches to three no matter what, maintaining a patch for this doesn't seem too bad, so it basically comes down to performance vs color correctness... 

Do we have any idea how common ICC profiles are in images that will cause this to be an issue? If I am understanding what this flag does, I imagine the vast majority of images we encounter will not have any color space conversion applied either way as they will already be in sRGB (which I assume is what it will try to convert "to" by default). If that assumption is correct, I would have a slight preference for 3 since then its only real con is maintaining the patch. 2 seems like the worst option since it maintains the con of having to maintain a patch but expands the con of incorrect rendering to Chrome unnecessarily.

**Comment by takahirox** [comment]
> convince upstream this is a good idea

I don't think it's a good idea because it can break the rendering results. Three.js won't accept it for sure.

> performance vs color correctness

As you see in https://github.com/mrdoob/three.js/issues/21318, not only color but also it can affect roughness or all others textures.

> Do we have any idea how common ICC profiles are in images that will cause this to be an issue?

No idea but I guess there are not so many.

**Comment by netpro2k** [comment]
> As you see in mrdoob/three.js#21318, not only color but also it can affect roughness or all others textures.
Yep fair enough. Still comes down to perf vs visual correctness. To me the performance benefit might be wroth it if most images would not be impacted anyway, but I don't feel very strong about that. Hopefully at some point we get to a place where most people are using compressed textures on everything anyway and this doesn't matter much anymore :)
