### ISSUE TITLE
links-button not completely clickable on mobile devices

### ISSUE THREAD

**Issue by postelontwerpen** [mozilla/hubs#4297]
**If I make a link to other rooms or to way-points (in Spoke and Hubs), the link on mobile devices is only clickable in the bottom part of the pink/red button.** 

- Issue on mobile devices in Chrome Safari and Firefox. 
- It concerns links in Spoke and links added in Hubs.
- The Button-text (visit link) also disappears on mobile.
- On desktop-browsers it works fine.

To illustrate the problem i made a small video where you can see me clicking in the top of the button (not working) and after that, at the bottom of the button (works)

https://user-images.githubusercontent.com/11406875/119941130-77bcf480-bf90-11eb-84f3-c211d65abb0e.mp4

Can you fix this?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-117)

**Comment by yakyouk** [comment]
I suspect this is a  problem of the button being too close to its mesh and not registering touch, as someone mentioned that scaling to 400% or 500% (which also scales the button's z-offset) seems to get the buttons to work reliably. Should be an easy fix.

**Comment by postelontwerpen** [comment]
thank you, @yakyouk 
I only can scale the link-asset in Spoke to a huge format. Than it is easier to click, that's true. But that didn't change the clickable region in the bottom of the button. I also put it in a complete empty scene. No change and mesh influence. Am I looking in the wrong place or direction?

**Comment by yakyouk** [comment]
hmm then maybe it's not that simple  XD

**Comment by yakyouk** [comment]
This seems to be due to a miscalculation of the tap coordinates within the aframe element, there seems to be a constant (in screen coordinates, i.e. *before* raycasting) negative vertical offset between the tap and where it hits in 3D.
When getting close to a button, it's not obvious since the button is big and the offset is small, relatively, but when far away, the offset may be larger than the button itself so the button isn't clickable.
