### ISSUE TITLE
hubs.mozilla.com doesn't load at all in internet explorer

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#430]
I don't expect us to have actual support for IE, but it seems that the page doesn't even load on IE11. We should have at least a warning message.

**Comment by johnshaughnessy** [comment]
Dumb question: Are edge and IE different? I just tried in Edge and our warning message shows up there. I don't have IE installed.

**Comment by cvan** [comment]
not a dumb question at all!

so, Edge is supported (and the default) on Windows 10. and, IE11 is supported on Windows 7, Windows 8.1, and Windows 10 (but not the default).

**Comment by gfodor** [comment]
I started a branch here since I wanted to see how feasible it was if we went 100% websockets:

https://github.com/mozilla/hubs/pull/575

As of this writing, we're still using data channels for unreliable transport, so this is still blocked. To actually get Edge working you'd need to tear down all the data channel setup completely since it errors out. (There's also an unsupported selector in master which is addressed in the PR.)

**Comment by arpu** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17929639-rtc-data-channels

there are many votes for the dataChannel for edge

**Comment by gfodor** [comment]
we now show a data channel warning.
