### ISSUE TITLE
HTC Vive Focus 3 controllers not working

### ISSUE THREAD

**Issue by tolen23** [mozilla/hubs#4436]
**Description**
When entering a Hubs room in VR with HTC Vive Focus 3 on Firefox Reality, the controllers do not show up. The only interaction possible is to exit to 2D Mode by pressing the A button (right controller).

**To Reproduce**
1. Put on HTC Vive Focus 3
2. Start Firefox Reality
3. Open https://hubs.mozilla.com/
4. Create room
5. Enter in VR

**Expected behavior**
Both controllers show up and I can use them for interactions

**Hardware** 
 - HTC Vive Focus 3
 - OS: Android
 - Browser: Firefox Reality 12.3

**Additional context**
This issue was also reported by user @jefmes in the Firefox Reality project: https://github.com/MozillaReality/FirefoxReality/issues/3945

However, I don't think that this can be solved solely on Firefox Reality side. I assume that it is also necessary to add something in Hubs, most likely here:
https://github.com/mozilla/hubs/blob/master/src/systems/userinput/devices/vive-controller.js
https://github.com/mozilla/hubs/blob/master/src/systems/userinput/userinput.js

When investigating the issue I found out that the controllers are actually there in the browser, but show up with id "HTC Vive 6DoF Controller" and (only) 3 buttons:

```
e.gamepad:
{ 
  id: "HTC Vive 6DoF Controller",
  index: 0, 
  mapping: "", 
  hand: "right", 
  displayId: 2, 
  connected: true, 
  buttons: (3) […], 
  axes: (2) […], 
  timestamp: 19907, 
  pose: GamepadPose
}
```

I was able to get the controllers working by basically adding a check for `gamepad.id === "HTC Vive 6DoF Controller"` everywhere in userinput.js and vive-controller.js where I found a check for `gamepad.id === "HTC Vive Focus Plus Controller"`, so that HTC Vive Focus 3 controllers are treated in the same way than HTC Vive Focus Plus controllers.

However, I did not create a PR for this because it is rather a dirty hack for two reasons:
* HTC Vive Focus 3 has more advanced controllers than HTC Vive Focus Plus from what I can see (especially more than 3 buttons). 
* I don't know if https://github.com/immersive-web/webxr-input-profiles/pull/199 (mentioned in https://github.com/MozillaReality/FirefoxReality/issues/3945) will lead to a changed gamepad,id, making in turn the fix useless again.

Any thoughts?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-65)

**Comment by crapshot1ai** [comment]
Has this issue been solved somehow? Or is there a solution to it? I just had the same issue. I am test running a vive focus 3 headset since we plan to buy a couple of them for teaching in vr ... planned to use mozilla hubs for that, but without proper working controllers this will not be working out

**Comment by jefmes** [comment]
> Has this issue been solved somehow? Or is there a solution to it? I just had the same issue. I am test running a vive focus 3 headset since we plan to buy a couple of them for teaching in vr ... planned to use mozilla hubs for that, but without proper working controllers this will not be working out

I personally wouldn't get the Focus 3 *right now* for Mozilla Hubs or any web based VR experiences. If you had not heard, Firefox Reality's development has been suspended entirely, and the project has been taken over by a team with Igalia and the browser will have the new name of "Wolvic." There has not been much movement on it so far externally, and HTC has yet to make any statements about being involved in Wolvic's development (I have asked but we haven't heard anything) so we effectively do not have a fully functioning, supported browser right now. I hope that changes soon because WebXR was one of the reasons I purchased a Focus 3, too.

**Comment by matthewbcool** [comment]
Thanks for your contributions to this thread @jefmes @crapshot1ai @tolen23. Closing this issue for now in favor of making a more general feature request since the status changes of FF reality. We can pick this up at https://github.com/mozilla/hubs/issues/4775
