### ISSUE TITLE
Hide volume controls for GIF

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#4502]
**Is your feature request related to a problem? Please describe.**

Our GIF plate has volume controls but GIF doesn't support audio. It would be confusing to users. We should hide volume controls for GIF.

![unknown](https://user-images.githubusercontent.com/7637832/128927806-23da2844-e8ef-4f9f-94e5-485a5706d3f2.png)

**Describe the solution you'd like**

Hide volume controls for GIF

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-743)

**Comment by keianhzo** [comment]
@takahirox I've tried adding through the place button, Spoke and just copy pasting the link I can't reproduce this for Gifs. How where you adding the gif? Can you share a gif link?

**Comment by takahirox** [comment]
Don't you see the GIF button in the place menu?

![image](https://user-images.githubusercontent.com/7637832/132035645-8b75c112-546c-44b6-86d9-c7d804c267b0.png)

**Comment by keianhzo** [comment]
That was the only method that I didn't try 😅

I've been debugging further and we are showing the controls in that case because the Reticulum media query API is returning mp4 instead of gifs for the gif backend. Looking into Reticulum I see that even though the gif backend is returning a few formats we specifically reduce to :
https://github.com/mozilla/reticulum/blob/b5680121d3ade221d6d3f862ff1fc9a70bdfcd99/lib/ret/media_search.ex#L780-L798

I don't see any issue to switch to gif on that one but my understanding is that we did that for a reason but I'm not sure: https://github.com/mozilla/reticulum/pull/119

Maybe @brianpeiris or @johnshaughnessy have some more background on that one.

**Comment by keianhzo** [comment]
Per our chat on the engineering meeting we want to keep using mp4 as the format from the gif backend and just (in general for videos) just remove the audio controls if there is no audio tracks.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue using the latest releases of Firefox and Chrome on Windows 10.
Now, the volume controls for GIFs are no longer displayed.
