### ISSUE TITLE
The client is translated and a new client is uploaded.  The name above the avatar. I can't see it.  How to solve it?  

### ISSUE THREAD

**Issue by justinzm** [mozilla/hubs#5279]
The client is translated and a new client is uploaded.  The name above the avatar. I can't see it.  How to solve it?

**Comment by matthewbcool** [comment]
Is this an issue related to the new name tags? If you are making a bug report, can you please provide the following details with steps to reproduce and your device information? Thank you.

Closing this issue for now but you are welcome to create a new one with the following information (using the bug report template):

**Description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**
Add any other context about the problem here.
