### ISSUE TITLE
Ошибка загрузки сцены 

### ISSUE THREAD

**Issue by skorolivesna** [mozilla/hubs#5404]
![image](https://user-images.githubusercontent.com/60566922/166101732-d0178cd0-c468-4788-a8f8-79aeae2db6fc.png)
Происходит ошибка загрузки сцены, при ее создании. 
Устройство: ноутбук
ОС: Windows 11 
Браузер: Яндекс

**Comment by Exairnous** [comment]
Не могли бы вы предоставить дополнительную информацию, например, какую сцену вы пытаетесь загрузить?
(переведено с английского через Google Translate)

**Comment by matthewbcool** [comment]
Could you please use the bug report template below in a new issue so that we can reproduce and understand the issue clearly. Thank you!

**Description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser: [e.g. Firefox]

**Additional context**
Add any other context about the problem here.
