### ISSUE TITLE
Can still hear friend even when very far away from them.

### ISSUE THREAD

**Issue by DillFrescott** [mozilla/hubs#5579]
**Description**
Can still hear friend even when very far away from them.

**Expected behavior**
I'd expect the roll off to eventually cut off the person's volume if I get far away from them.

**Screenshots**
n/a

**Hardware** 
 - Device: Windows Desktop
 - OS: Windows 11
 - Browser: Brave

**Additional context**
n/a

**Comment by DillFrescott** [comment]
Ok I learned that you can import the map into Spoke and just change the master avatar audio settings to account for this. I guess it could technically be a solution

**Comment by emclaren** [comment]
Hi, audio roll off is dependant on how the settings are changed in Spoke. There is more work that we could be done to surface audio controls in world. We are looking into adding audio improvements to our roadmap. 

There is a (somewhat old) ticket that goes through some audio improvements here: https://github.com/mozilla/hubs/issues/2305.

I'm going to close this issue for now since it sounds like the tech was behaving as expected, but improving this is something our team is aware of and would like to improve.
