### ISSUE TITLE
Error: Failed to find Electron v2.0.2 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.2/electron-v2.0.2-darwin-arm64.zip

### ISSUE THREAD

**Issue by mikemainguy** [mozilla/hubs#5655]
**Description**
checkout master and run npm ci, receive error on mac m1:
 Error: Failed to find Electron v2.0.2 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.2/electron-v2.0.2-darwin-arm64.zip

**To Reproduce**
1. checkout master (hub-cloud also fails with same error)
2. run npm ci
3. build doesn't complete

**Expected behavior**
Expected command to complete

**Screenshots**

**Hardware** 
 - Mac M1 (not M1 Max)
 

**Additional context**
- Node v16.16.0
 - npm v8.11.0

**Comment by matthewbcool** [comment]
Thanks for submitting.
Related: 
https://github.com/mozilla/hubs/discussions/5603
https://github.com/mozilla/hubs/pull/5621

**Comment by knev** [comment]
I'm also getting this.

**Comment by rawnsley** [comment]
I get this as well and the cause is a bit opaque as the `electron` package is not an obvious dependency of the project. I believe it is being downloaded by [an installation script](https://github.com/electron/electron/blob/main/npm/install.js) and that the problem has been addressed, more or less, in the root project in response to [this issue](https://github.com/electron/electron/pull/32266).

**Comment by epleaner** [comment]
Also getting this on Mac M1.
