### ISSUE TITLE
Should not allow to change name to empty string 

### ISSUE THREAD

**Issue by mMARUF** [mozilla/hubs#5686]
**OS:**
macOS Monterey version: 12.5.1

**Browser:**
Chrome Version 104.0.5112.101

**Steps to Reproduce:**
1) Go to https://hubs.mozilla.com/
2) Inside a room change the name to empty string

**Actual Result:**
System allows changing name to empty string

**Expected Result:**
System should not allow changing name to empty string

**Attachment:**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/45368054/187301119-be3ad0ec-5707-466a-876e-7fd5f4eaf5a1.gif)

**Comment by matthewbcool** [comment]
Thanks for your report. I don't personally have a strong opinion about if we should allow empty strings as user names. I don't think this is a clear bug because I can see use cases where setting the user name to an empty string is an advantage. 

We can leave this issue up for more discussion around this topic. Thanks again for bringing it up.

**Comment by Exairnous** [comment]
I don't really have a strong opinion on this, but I don't see any harm in allowing a name with just spaces.  @mMARUF  is there some downside I'm not seeing?  @matthewbcool I'm also not seeing what the advantage really is since the name tag background is still shown (before I occasionally used it for taking name tags out of Hubs camera pictures, and combining it with an invisible avatar to be able to move around undetected, but with the new name tag backgrounds that isn't possible anymore. One possibility might be to use it for recording to minimize visual noise?)

Maybe we should do a pro/con list to clarify the matter?

**Comment by matthewbcool** [comment]
Closing this issue as it's a better design discussion and not a clear bug. We can continue any further discussion in the #design channel of the hubs discord server. Please add the designer role to participate: https://discord.gg/yRgyeS3ShC
