### ISSUE TITLE
bitECS - Some scene changes broken with "tried loading multiple nav mesh"

### ISSUE THREAD

**Issue by mikemorran** [mozilla/hubs#6316]
**Description**
We encountered this at last friday's meetup. Changing scenes to certain environments freezes the screen and we see a nav.js line 14 error "tried loading multiple nav meshes".

**To Reproduce**
1. Go to a room with new loader enabled
2. Attempt to change scenes to this url: https://hubs.mozilla.com/scenes/0MdfQwB/cloud-nine

**Expected behavior**
The scene change should complete without errors.

**Comment by takahirox** [comment]
From this code

https://github.com/mozilla/hubs/blob/e6e92b8291cf83db9df1c097725d15deb7974f10/src/systems/nav.js#L13-L16

With the new loader, the old nav mesh doesn't seem to be released in a proper way. But as the code indicates, it `nav.loadMesh()` seems to release the old one as fallback so perhaps not a serious problem.

Yes, the old nav mesh should be released with a proper way and should be no error, but we may remove P1 label because probably functionality is ok.

**Comment by keianhzo** [comment]
It seems that it's actually related with an exception loading invalid particle images. It seems that Aframe caught those exceptions as we were are the same thing in the AFrame system. I've opened a PR to fix this.

**Comment by takahirox** [comment]
By the way @keianhzo what do you think of the console error? Does it happen because the scene has multiple nav meshes? If so, with the new loader multiple nav meshes in a scene is not accepted (while with the old loader they are accepted)?

**Comment by keianhzo** [comment]
It was actually a difference between how we were processing the nav-mesh in the old and new loader, I've opened a PR: https://github.com/mozilla/hubs/pull/6326
