### ISSUE TITLE
bitECS: No object menu on broken media link object

### ISSUE THREAD

**Issue by takahirox** [mozilla/hubs#6334]
Reported by Imaginer @Exairnous on Discord

**Description**

With the new loader enabled object menus are not shown on broken media link objects

**To Reproduce**
1. Enter a room with the new loader
2. Place an object that creates broken media link object (How for testing?)
3. Hover the cursor on the object
4. Press the space bar
5. Confirm that no object menu is shown on the object

**Expected behavior**

The menu is shown on broken media link objects as with the old loader

**Screenshots**

![image](https://github.com/mozilla/hubs/assets/7637832/bbddb802-daf6-431e-9e86-dbac4e25ae29)

Pressing the space bar but no menu

**Hardware** 
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome

**Additional context**

Thinking of the priority... If there is no way to remove broken link objects it can be P1?

**Comment by Exairnous** [comment]
To test you can simply paste in this link: https://not.valid/
I would agree with it being P1 as broken links don't show in the object menu (another bug) and there is no way to remove them except by the person who spawned them refreshing their page.

Broken links also show up when you locally upload unrecognized, but valid, files for sharing (this is normal and happens in the aframe loader as well), e.g. text files, so there needs to be a way to use the open link button to download them (this all works fine in the aframe loader because the menu is shown on broken links).

**Comment by keianhzo** [comment]
I believe this is already fixed in the production code. Closing for now, let me know if I should reopen.

**Comment by Exairnous** [comment]
Yup, seems fixed.  Thanks!
