### ISSUE TITLE
Вы вруны и лицемеры Mozilla!

### ISSUE THREAD

**Issue by erikobox** [mozilla/hubs#6486]
Зачем вывесили гордо это на GitHub, он не устанавливается, думаю вы это сделали намеренно. Когда Цукерберг начал хайпить метаверс, вы решили прыгнуть на хайптрейн, а теперь удалили сервис, а тут написали типа вы за опер сорс. А не устанавливается ваш Hubs локально.

Вы пишите клонировать репозиторий и написать npm ci, так вот это не работает. Пробовал рекомендованную 16.16.0 Node.js версию, но нет, не устанавливается. Вы вруны и лицемеры Mozilla!

**Comment by erikobox** [comment]
Установился версии Node.js 16.20.0

**Comment by Exairnous** [comment]
There's no need for name calling here.  Hubs was around long before the metaverse started being hyped by Mark Zuckerberg and will hopefully be around long after he's lost interest.

Hubs requires more than just this one repository to be usable by an end user.  If you want to run Hubs locally, then I'd suggest looking into https://github.com/mozilla/hubs-compose and using that to build a minimal stack.  See this YouTube tutorial for a walkthrough on how to run hubs-compose.
https://www.youtube.com/watch?v=BULDwyiNLzU

**Comment by erikobox** [comment]
Вы же все равно выложили исходный код, почему бы не сделать установку похожей на установку PHP форума, что бы люди у себя на сайте открыли 3D/VR измерение. А так зачем столько мороки, я не хочу хостить копию сервиса Hubs, мне нужен только один мир, который бы открывался по ссылке домена моего сайта. И чтобы я мог редактировать мир из админки, все.

Люди с 90-х хотят такие сайты, но из 8 миллиардов людей только вы можете такое сделать. Вместо этого вы занимаетесь ерундой. Жалко в первую очередь программистов, что столько работы сделали низа что.

Mozilla хватит отставать от Google, дай нам 3 измерение, верни нормальный браузер с 3D инспектором сайта. Создавай инновации, вместо того чтобы догонять Google и Meta.

**Comment by Exairnous** [comment]
If you "only need one world that would open via a link to the domain of my site. And so that I can edit the world from the admin panel" and don't want to deal with setting up the complexities of the whole Hubs stack, then I would suggest using a service that manages the hosting for you like https://virtuallinkhosting.com/

Creating 3D virtual worlds is complex, there's a lot of technology that has to be handled.  If you want something with a simpler setup that's more like the 2000s web, you might want to check out https://webspaces.space/introduction.html
