### ISSUE TITLE
Chat box inside the room

### ISSUE THREAD

**Issue by BhuvanaMeenakshiK** [mozilla/hubs#810]

**Comment by brianpeiris** [comment]
In case you missed it, there is actually a chat box in the bottom left corner after you've entered the room:

![image](https://user-images.githubusercontent.com/79419/50569623-a2061b80-0d1e-11e9-81c6-f196d8d97f62.png)

If you're referring to using text chat from inside a VR headset, we've considered solutions to this but have avoided it so far since typing in VR can be difficult for chat especially. 

Thanks for the suggestion either way, it's good to know what problems people are running into.

**Comment by BhuvanaMeenakshiK** [comment]
> In case you missed it, there is actually a chat box in the bottom left corner after you've entered the room:
> 
> ![image](https://user-images.githubusercontent.com/79419/50569623-a2061b80-0d1e-11e9-81c6-f196d8d97f62.png)
> 
> If you're referring to using text chat from inside a VR headset, we've considered solutions to this but have avoided it so far since typing in VR can be difficult for chat especially.
> 
> Thanks for the suggestion either way, it's good to know what problems people are running into.

Yes I went through the chat box here after a long time of search (because the UI was very light in color and could not be differentiated  until I started to type). But it could be better enough if it displayed against the avatar of each person. Also I saw the messages disappearing in a while, this is not effective when new users join the group. Because if anything important discussed or some links been shared over then the messages should be available everytime for future reference.

And absolutely fair enough to the fact that it becomes useless when VR heaset is used but a virtual keyboard can still be added to type the messages. The reason why I am insisting on the textual input is that last time I hosted a small conference among the Mozillians of my region and due to some problem of mic people were not able to interact with each other so we took the help of the message box to continue our converssation.

**Comment by brianpeiris** [comment]
Cool, so there are a few things to unpack here, that may be split into separate issues:

1. Make the existing chat box easier to spot when you're in the room
    This is probably just a matter of adding some contrast to it so that it's visible in both light and dark scenes.
2. Add the ability to send a message to individual users. 
    I believe this will require some backend work, since we don't have a way to direct messages to a particular user at the moment, IIRC. 
    If the backend were in place already, we'd have to decide how to expose it in the client -- one idea I can think of is to add a "Message" button to each avatar in pause mode and that message button just focuses the existing chat box and populates it with a new `/whisper <avatar-name> <msg>` command, although that idea might fall apart if there are multiple avatars with the same name in the room.
3. Add the ability to persist and view the chat history of a room
    We've talked about this on our team and decided that it will need some consideration since it changes the meaning of chat messages. At the moment chat messages are intentionally ephemeral, this gives us several useful properties. 
    For example, if someone spams chat, or posts something inappropriate or by mistake, it just fades away and we don't have to worry about adding chat moderation. It also helps circumvent privacy issues, so that if you post some private information to chat, we don't have to worry about deleting that later on if you decide you no longer want it in chat history.

I'll let the rest of the team chime in here as well.

**Comment by gfodor** [comment]
thanks for opening this issue and thanks to both of you for offering to assist us in improving the chat! the current chat was designed/implemented in a few days and so is very basic, but (as you can probably see) it has proven way better than not having chat at all :)

some additional color on the future design plans we have, PRs and feedback welcome ofc:

- We want to make sure chat becomes a central focus of the experience on both desktop and phone, so this will mean moving the chat to the center, increasing the contrast a bit so it's more noticeable, and adding it on mobile screens as well. The current "joysticks" we have on mobile should only show in landscape mode and the big center spawn button should be removed, in favor of the spawn button on the left of the chat (as well as a tooltip introducing the user to spawning until they click it the first time.)

- Additionally, photo and attach buttons will be added to the chat text box, to replace the attach file and post photo flows available on desktop and mobile respectively. To increase real estate, the "Send" button will become the usual paper airplane icon.

- Chat history definitely seems like it could be a great feature, another design challenge in addition to the ones brian mentioned is we do not want the history to visibly get in the way of seeing the room. (This is another reason why we started with expiring messages so if you just wait then any visibility issues will go away.) We think the right design is one where if you scroll on the chat messages then you will see the history, which is normally hidden, but we haven't prototyped a good solution yet.

- Private messages seem like a great idea -- however since you can't type in VR, it could be problematic since if you DM someone and don't know they're using VR, they will not have a way to respond (which could lead you to think they are ignoring you!) Typing in VR is going to be tough, we would need to integrate a in-game VR keyboard and also a in-game text box UI, both of which are pretty difficult to do in a way that will run well on mobile VR headsets.

**Comment by Mordax** [comment]
@gfodor @brianpeiris Sorry for the late reply, I'm definitely still around. I'm gonna do the contrast adjustment on the existing chat box as a way to get acquainted with the code base, and build on complexity from there. I agree, it may be better to split some of these into separate issues. Quick question though - is there anyway to test the VR without having a peripheral? I'm not rich enough yet to afford one :) . 

So it seems that Hubs is really aiming to be something used for professional meetings, correct? Maybe it would be prudent to allow exportation of this hypothetical historical chat into a file so people can go over what was discussed in the meeting. 

@netpro2k MMORPGs are great for inspiration. I also have spent some time in Second Life-esque software so those are some places to look to to see what issues they've overcome.

**Comment by gfodor** [comment]
the chat box has been redesigned to be more visible, etc. please re-open if there are further suggestions, thanks!
